[DOCS] Theme selector
great-expectations/great_expectations pull request #10181
Opened 2024-08-07 19:58 UTC by deborahniesz

- [ ] Description of PR changes above includes a link to [an existing GitHub issue](https://github.com/great-expectations/great_expectations/issues)
- [ ] PR title is prefixed with one of: [BUGFIX], [FEATURE], [DOCS], [MAINTENANCE], [CONTRIB]
- [ ] Code is linted - run `invoke lint` (uses `ruff format` + `ruff check`)
- [ ] Appropriate tests and docs have been updated

For more information about contributing, see [Contribute](https://docs.greatexpectations.io/docs/contributing/contributing_checklist).

After you submit your PR, keep the page open and **monitor the statuses of the various checks made by our continuous integration process at the bottom of the page. Please fix any issues that come up** and [reach out on Slack](https://greatexpectations.io/slack) if you need help. Thanks for contributing!

2024-08-22 17:33 UTC, josectobar commented
It's not related to these changes, but we need to fix the font color of the privacy link in light mode. It seems to be hidden. 
![2024-08-22 10 31 46](https://github.com/user-attachments/assets/ea928217-6007-43f4-9b9f-9b5a61bea517)

2024-08-22 17:41 UTC, josectobar commented
Could we remove the white borders in the code snippet boxes for dark mode? 

![image](https://github.com/user-attachments/assets/43bf3847-6df8-4216-afc7-9ff70abc9ef6)

2024-08-22 17:44 UTC, josectobar commented
some embeded span texts are shown with a white background, can we remove the background and the border?

before: 
![image](https://github.com/user-attachments/assets/ed8b4181-4fd3-4c31-98bb-5d15c1e6942e)


after:

![image](https://github.com/user-attachments/assets/5ec84524-5bc5-43ad-98f5-aab82c44a31b)

2024-08-22 17:53 UTC, josectobar commented
We should also change the white background and text color from docs/reference/api/core/util code snippets:

before: 

![image](https://github.com/user-attachments/assets/f30d1ce0-34aa-4d1f-90b6-4bdc162d4502)


after:

![image](https://github.com/user-attachments/assets/50b9f787-f4f0-4b95-b363-5b911bf8a81c)

2024-08-22 17:55 UTC, josectobar commented
The disabled state of the submit button in the feedback modal lack contrast: 
![image](https://github.com/user-attachments/assets/73a4c1b8-3bc6-4767-8896-1f9eb60f502b)

2024-08-22 18:11 UTC, josectobar commented
There are some screenshots with white backgrounds. Are we planning on replacing these at some point? 
![image](https://github.com/user-attachments/assets/f30d8852-550d-46bd-8180-a48649273ffb)

2024-08-22 18:17 UTC, josectobar requested changes
Great work! I left a couple of comments related to the code and some others related to specific cases where I think we need to adjust some of the styling for dark mode. cc. @SuperYeehee

2024-08-22 18:17 UTC, josectobar commented on docs/docusaurus/src/components/WasThisHelpful/styles.module.scss
> +        box-shadow: 0 3px 6px #00000029;
Can we make these variables? I see we use them in a couple of places.

2024-08-22 18:17 UTC, josectobar commented on docs/docusaurus/src/css/custom.scss
> +  --ifm-background-color: #262626;
Can we add these hex to their  own var and then just reference them here instead of repeating them?

2024-08-22 18:24 UTC, SuperYeehee commented
> Great work! I left a couple of comments related to the code and some others related to specific cases where I think we need to adjust some of the styling for dark mode. cc. @SuperYeehee

Could you clarify what you mean on "Adjust some of the styling for DM?" Are you references like a set of standard variables like we use in our GX theme.ts?

2024-08-22 18:31 UTC, josectobar commented
> > Great work! I left a couple of comments related to the code and some others related to specific cases where I think we need to adjust some of the styling for dark mode. cc. @SuperYeehee
> 
> Could you clarify what you mean on "Adjust some of the styling for DM?" Are you references like a set of standard variables like we use in our GX theme.ts?

@SuperYeehee , I'm referring to my comments above☝🏽

2024-08-30 16:08 UTC, josectobar commented on docs/docusaurus/src/css/api_docs/api_docs.scss
> +         background-color: #404041;
```suggestion
         background-color: var(--payne-gray-color);
```

2024-08-30 16:13 UTC, josectobar commented on docs/docusaurus/src/css/api_docs/pydata-sphinx-theme-modified.scss
> +  box-shadow: none !important;
Does this work without the `!important`?

2024-08-30 16:23 UTC, josectobar commented on docs/docusaurus/src/css/api_docs/pydata-sphinx-theme-modified.scss
> +  border: 1px solid #E54F54;
```suggestion
  border: 1px solid var(--ifm-color-warning-dark);
```

2024-08-30 16:23 UTC, josectobar commented on docs/docusaurus/src/css/api_docs/pydata-sphinx-theme-modified.scss
> +    border-color: #E54F54;
```suggestion
    border-color: var(--ifm-color-warning-dark:);
```

2024-08-30 16:24 UTC, josectobar commented on docs/docusaurus/src/css/api_docs/pydata-sphinx-theme-modified.scss
> +    background-color: #b6c64733;
```suggestion
    background-color: var(--ifm-color-success-dark);
```

2024-08-30 16:25 UTC, josectobar commented on docs/docusaurus/src/css/api_docs/pydata-sphinx-theme-modified.scss
> +    border-color: #b6c647;
```suggestion
    border-color: var(--ifm-color-success-dark);
```

2024-08-30 16:25 UTC, josectobar commented on docs/docusaurus/src/css/api_docs/pydata-sphinx-theme-modified.scss
> +  border: 1px solid #B6C647;
```suggestion
  border: 1px solid var(--ifm-color-success-dark);
```

2024-08-30 16:33 UTC, josectobar approved these changes
Looks great! I love dark mode! please address some final suggestions but otherwise is good to go.

2024-09-02 20:21 UTC, merged