[MAINTENENCE] Add metadata to UnexpectedRowsExpectation
great-expectations/great_expectations pull request #10311
Opened 2024-08-29 22:40 UTC by ashmortar

Adds metadata to the UnexpectedRowsExpectation and updates its docstring to more closely match core Expectations.  Also makes description and instance variable.

- [ ] Description of PR changes above includes a link to [an existing GitHub issue](https://github.com/great-expectations/great_expectations/issues)
- [x] PR title is prefixed with one of: [BUGFIX], [FEATURE], [DOCS], [MAINTENANCE], [CONTRIB]
- [x] Code is linted - run `invoke lint` (uses `ruff format` + `ruff check`)
- [x] Appropriate tests and docs have been updated

For more information about contributing, see [Contribute](https://docs.greatexpectations.io/docs/contributing/contributing_checklist).

After you submit your PR, keep the page open and **monitor the statuses of the various checks made by our continuous integration process at the bottom of the page. Please fix any issues that come up** and [reach out on Slack](https://greatexpectations.io/slack) if you need help. Thanks for contributing!

2024-08-29 22:53 UTC, ashmortar commented
> A new contributor, HUZZAH! Welcome and thanks for joining our community. In order to accept a pull request we require that all contributors sign our Contributor License Agreement. We have two different CLAs, depending on whether you are contributing to GX in a personal or professional capacity. Please sign the one that is applicable to your situation so that we may accept your contribution:
> 
> [Individual Contributor License Agreement v1.0](https://docs.google.com/forms/d/e/1FAIpQLSdA-aWKQ15yBzp8wKcFPpuxIyGwohGU1Hx-6Pa4hfaEbbb3fg/viewform?usp=sf_link) [Software Grant and Corporate Contributor License Agreement v1.0](https://docs.google.com/forms/d/e/1FAIpQLSf3RZ_ZRWOdymT8OnTxRh5FeIadfANLWUrhaSHadg_E20zBAQ/viewform?usp=sf_link)
> 
> Once you have signed the CLA, you can add a comment with the text `@cla-bot check` and the bot will update the PR status!
> 
> Please reach out to the #gx-community-support channel, on our [Slack](https://greatexpectations.io/slack) if you have any questions or if you have already signed the CLA and are receiving this message in error.
> 
> Users missing a CLA: ashmortar

@cla-bot check

2024-09-03 14:50 UTC, NathanFarmer requested changes
Nice work! Very close to ready. I would go ahead and covert this from draft once you make the changes.

2024-09-03 14:50 UTC, NathanFarmer commented on great_expectations/expectations/expectation.py
> +SUPPORTED_DATA_SOURCES = ["SQL", "Spark-SQL"]
This should be left as an empty list `[]`. This is probably supported by many (if not all) OSS data sources, but I'm not sure what level of testing has been done, and this metadata field isn't used anywhere today. The level of abstraction that we use for this field is more like `["Snowflake", "Postgres", ...]`.

2024-09-03 14:50 UTC, NathanFarmer commented on great_expectations/expectations/expectation.py
> +    "This Expectation will fail validation if the query returns one or more rows.  "
Nit: 2 spaces after period should be 1

2024-09-03 14:50 UTC, NathanFarmer commented on great_expectations/expectations/expectation.py
> +    """
Nice work on the docstring! I would remove the supported datasource blob for now. Docs team can add this if they want it.

2024-09-03 14:50 UTC, NathanFarmer commented on great_expectations/expectations/expectation.py
> +
You shouldn't need to add anything at the class-level now that you made the changes in the `Expectation` superclass.

2024-09-03 14:50 UTC, NathanFarmer commented on great_expectations/expectations/expectation.py
> +SUPPORTED_DATA_SOURCES = ["SQL", "Spark-SQL"]
You can just get rid of the variable and pass `[]` in the `schema_extra` like you did for `data_quality_issues`.

2024-09-04 16:30 UTC, NathanFarmer approved these changes

2024-09-04 16:59 UTC, merged