[DOCS] Add Connect to Databricks SQL page in GX Cloud
great-expectations/great_expectations pull request #10394
Opened 2024-09-13 21:14 UTC by allisongx

https://greatexpectations.atlassian.net/browse/LAK-1211

- [ ] Description of PR changes above includes a link to [an existing GitHub issue](https://github.com/great-expectations/great_expectations/issues)
- [ ] PR title is prefixed with one of: [BUGFIX], [FEATURE], [DOCS], [MAINTENANCE], [CONTRIB]
- [ ] Code is linted - run `invoke lint` (uses `ruff format` + `ruff check`)
- [ ] Appropriate tests and docs have been updated

For more information about contributing, see [Contribute](https://docs.greatexpectations.io/docs/contributing/contributing_checklist).

After you submit your PR, keep the page open and **monitor the statuses of the various checks made by our continuous integration process at the bottom of the page. Please fix any issues that come up** and [reach out on Slack](https://greatexpectations.io/slack) if you need help. Thanks for contributing!

2024-09-17 21:44 UTC, jtimberman requested changes

2024-09-17 21:44 UTC, jtimberman commented on docs/docusaurus/docs/cloud/connect/connect_databrickssql.md
> +- To improve data security, GX recommends creating a separate Databricks SQL user for your GX Cloud connection.
`s/user/service principal/` - Per Databricks [documentation](https://docs.databricks.com/en/admin/users-groups/service-principals.html), a service principal, not a user, should be used for automated tools.

2024-09-18 13:31 UTC, Kilo59 approved these changes
Agree with @jtimberman suggestion, but otherwise LGTM.

2024-09-18 17:54 UTC, jtimberman approved these changes
🧱🧱🧱🧱🧱 🥳

2024-09-18 18:25 UTC, merged