[DOCS] dbt Tutorial created in collaboration with Jonathan Porter
great-expectations/great_expectations pull request #10458
Opened 2024-10-02 21:36 UTC by r34ctor

This is a tutorial designed to demonstrate how dbt, GX, Airflow and Postgres can all work together. The tutorial was written by Jonathan Porter, and I have made edits and contributed wherever possible and/or required.

- [x] Description of PR changes above includes a link to [an existing GitHub issue](https://github.com/great-expectations/great_expectations/issues)
- [x] PR title is prefixed with one of: [BUGFIX], [FEATURE], [DOCS], [MAINTENANCE], [CONTRIB]
- [x] Code is linted - run `invoke lint` (uses `ruff format` + `ruff check`)
- [x] Appropriate tests and docs have been updated

For more information about contributing, see [Contribute](https://docs.greatexpectations.io/docs/contributing/contributing_checklist).

After you submit your PR, keep the page open and **monitor the statuses of the various checks made by our continuous integration process at the bottom of the page. Please fix any issues that come up** and [reach out on Slack](https://greatexpectations.io/slack) if you need help. Thanks for contributing!

2024-10-03 22:24 UTC, mikrdgz approved these changes

2024-10-03 22:24 UTC, mikrdgz commented on docs/docusaurus/docs/reference/learn/data_quality_use_cases/dbt_tutorial.md
> +This tutorial will enable you to schedule and run data pipelines locally using PostgreSQL as the database, dbt for transforming data, Great Expectations for data quality and Airflow for workflow orch
In general, our docs use the second-person perspective ("You can install...")versus first person as you've mixed in here ("We can install..."). And is directive versus conversational. What I'm describing is generally the industry standard and is easier to follow for users who are performing an operation. Our [existing core docs](https://docs.greatexpectations.io/docs/core/define_expectations/create_an_expectation) are a good example.

2024-10-03 22:24 UTC, mikrdgz commented on docs/docusaurus/docs/reference/learn/data_quality_use_cases/dbt_tutorial.md
> +## Requirements
Change Requirements section to Prerequisites and add these bullets from the intro paragraph:

- Basic knowledge of Python, SQL, Docker.
- Familiarity with using CLIs.

 See our existing docs for how we do this.

2024-10-03 22:24 UTC, mikrdgz commented on docs/docusaurus/docs/reference/learn/data_quality_use_cases/dbt_tutorial.md
> +In addition to the requirements below, we recommend using an IDE like VSCode to organize your project.
Format these kinds of asides as:

:::note
content goes here 
:::

2024-10-03 22:24 UTC, mikrdgz commented on docs/docusaurus/docs/reference/learn/data_quality_use_cases/dbt_tutorial.md
> +## Clone the github repo
GitHub. Also we number operation steps in our docs currently,  e.g., 1. Clone the GitHub repo

2024-10-03 22:24 UTC, mikrdgz commented on docs/docusaurus/docs/reference/learn/data_quality_use_cases/dbt_tutorial.md
> +## Clone the github repo
Open a terminal window and navigate to the folder you want to use for this tutorial. Next, clone the [example GitHub repo](https://github.com/greatexpectationslabs/dbt-tutorial) for this project by running the code below in your terminal.

2024-10-03 22:24 UTC, mikrdgz commented on docs/docusaurus/docs/reference/learn/data_quality_use_cases/dbt_tutorial.md
> +Let's take a moment to explain some of the contents of the configuration we have just cloned.
Replace with "The project contains the following files:"

2024-10-03 22:24 UTC, mikrdgz commented on docs/docusaurus/docs/reference/learn/data_quality_use_cases/dbt_tutorial.md
> +There’s a lot to unpack here, so we will cover the main points:
Too conversational. Please review the existing docs and try and emulate the tone.

2024-10-03 22:24 UTC, mikrdgz commented on docs/docusaurus/docs/reference/learn/data_quality_use_cases/dbt_tutorial.md
> +- Inside the `dbt.Dockerfile`, we tell Docker to copy our dbt folder into the container and install dbt dependencies. In this case, we install dbt-postgres since we are using PostgreSQL as our databa
The `dbt.Dockerfile` contains code that copies the dbt folder into a Docker container and installs all necessary dbt dependencies, including `dbt-postgres`. This package is necessary to use dbt with a PostgreSQL database. 

^^^ This is the type of tone we use in the docs, try to emulate the existing docs when possible.

2024-10-03 22:24 UTC, mikrdgz commented on docs/docusaurus/docs/reference/learn/data_quality_use_cases/dbt_tutorial.md
> +- We added a line (line 11) to export the credentials from our credentials file when we connect to the Docker container. This is not the only way to achieve this, but just one example.
Line 11 exports the credentials from the credentials file when connecting to the Docker container. 


(no need to cover all possible avenues, leave the line about the other possibilities out as its vague)

2024-10-03 22:24 UTC, mikrdgz commented on docs/docusaurus/docs/reference/learn/data_quality_use_cases/dbt_tutorial.md
> +- Starting on line 97, you’ll notice that Airflow is a collection of 4 different services: an initialization service (run the first time we run the service), a webserver (the website we connect to to
In the future, just enter the code snippet in the doc itself versus referring to the code. It's much easier for the user to just see the snippet you're talking about versus having to switch back and forth between the docs and their project.

Airflow is a collection of 4 different services: an initialization service (this happens when you first run the service), a web server, a scheduler, and a PostgreSQL backend that stores metadata about this pipeline.

2024-10-03 22:24 UTC, mikrdgz commented on docs/docusaurus/docs/reference/learn/data_quality_use_cases/dbt_tutorial.md
> +- On line 159, you will see a network section where we define a default network for all of the services to communicate on. This also allows us to use the service names as the host name in credentials
Line 195 defines a default network for all services in this pipeline. This section also defines the services' names as the host name in credentials, instead of using an IP address.

2024-10-03 22:24 UTC, mikrdgz commented on docs/docusaurus/docs/reference/learn/data_quality_use_cases/dbt_tutorial.md
> +- Finally, on line 165, we specify Docker secrets to show how to securely pass in our ssh keys into the containers that will use them.
Line 165 demonstrates how to securely pass ssh keys using Docker secrets to the containers in the pipeline. We recommend using this pattern as a best practice.

2024-10-03 22:24 UTC, mikrdgz commented on docs/docusaurus/docs/reference/learn/data_quality_use_cases/dbt_tutorial.md
> +We are now ready to start up our services and start working with them. In the next few steps we will also show you how to connect to each service and work with it. Make sure you have Docker Desktop o
Ensure Docker desktop is open and running. Next, you will initialize and connect each of the services in this example using the commands below.

2024-10-03 22:24 UTC, mikrdgz commented on docs/docusaurus/docs/reference/learn/data_quality_use_cases/dbt_tutorial.md
> +When you run this for the first time, it may take several minutes to download and install the required libraries. You will also notice that one of the services `airflow-init` exits after running, but
Put the "You will notice..." aside in a :::note :::

2024-10-03 22:24 UTC, mikrdgz commented on docs/docusaurus/docs/reference/learn/data_quality_use_cases/dbt_tutorial.md
> +One of the services we are running with Docker is pgAdmin, which will let you interact with the PostgreSQL database. We will be using pgAdmin in this tutorial, but feel free to use a SQL editor of yo
This tutorial uses pgAdmin to interact with the PostgreSQL database, but you can use the SQL editor of your choice.

2024-10-03 22:24 UTC, mikrdgz commented on docs/docusaurus/docs/reference/learn/data_quality_use_cases/dbt_tutorial.md
> +Log in using the credentials specified in docker compose for pgAdmin:
Docker. Don't forget to capitalize proper nouns in this tutorial

2024-10-03 22:24 UTC, mikrdgz commented on docs/docusaurus/docs/reference/learn/data_quality_use_cases/dbt_tutorial.md
> +- Right click on Servers in the top left corner and choose Register > Server
In our docs we **bold** UI elements

2024-10-03 22:24 UTC, mikrdgz commented on docs/docusaurus/docs/reference/learn/data_quality_use_cases/dbt_tutorial.md
> +> Here we are using the docker exec command to open an interactive terminal inside the container using bash as the shell. The -l flag is important here because it tells the shell to be a login shell
This can be a :::note:::

2024-10-03 22:24 UTC, mikrdgz commented on docs/docusaurus/docs/reference/learn/data_quality_use_cases/dbt_tutorial.md
> +Once inside the dbt container, run the `dbt deps` command to install dependencies. Next, copy the seed data into the seeds folder by running `cp jaffle-data/*.csv` and then run the `dbt seed` command
Next, run the `dbt debs` command....

Avoid using once because it is a word with several meanings here

2024-10-03 22:24 UTC, mikrdgz commented on docs/docusaurus/docs/reference/learn/data_quality_use_cases/dbt_tutorial.md
> +Again, we can see the models successfully created as tables and views but in our public schema:
You will see the models have been created successfully as tables and views within the public schema.

2024-10-03 22:24 UTC, mikrdgz commented on docs/docusaurus/docs/reference/learn/data_quality_use_cases/dbt_tutorial.md
> +Exit the dbt Docker container's terminal by running:
To exit the dbt Docker container's terminal, run the following command:

2024-10-03 22:24 UTC, mikrdgz commented on docs/docusaurus/docs/reference/learn/data_quality_use_cases/dbt_tutorial.md
> +## Use Great Expectations to create Data Quality Tests
according to the docs style guide, titles are sentence case meaning you only capitalize the first word and proper nouns

2024-10-03 22:24 UTC, mikrdgz commented on docs/docusaurus/docs/reference/learn/data_quality_use_cases/dbt_tutorial.md
> +We will be following the [GX getting started guide](https://docs.greatexpectations.io/docs/oss/get_started/get_started_with_gx_and_sql), but running it inside Docker. There are a number of ways you c
In the next section of this tutorial, you will follow the [Getting Started](https://docs.greatexpectations.io/docs/oss/get_started/get_started_with_gx_and_sql) guide to run GX with SQL within a Docker container. This guide describes the process using Jupyter Notebook, although you can use any Python development tool you prefer.

2024-10-03 22:24 UTC, mikrdgz commented on docs/docusaurus/docs/reference/learn/data_quality_use_cases/dbt_tutorial.md
> +Run the following command in our project’s terminal to start the Jupyter Notebook Server:
Run the following command within the project directory to start the Jupyter Notebook server:

2024-10-03 22:24 UTC, mikrdgz commented on docs/docusaurus/docs/reference/learn/data_quality_use_cases/dbt_tutorial.md
> +![Emptyer Jupyter Notebook Server](./dbt_tutorial/empty_jupyter_notebook_server.png)
Next time add this as an example code snippet of what the user will see versus a screenshot. Try and use code snippets versus screenshots of code when possible

2024-10-03 22:24 UTC, mikrdgz commented on docs/docusaurus/docs/reference/learn/data_quality_use_cases/dbt_tutorial.md
> +Create a new notebook. In the top left corner choose File > New > Notebook. Then select the Python 3 Kernel if prompted.
To create a new notebook, navigate to **File > New > Notebook** in the top left menu, then select **Python 3 Kernel** when prompted.

usually you'd want to avoid a screenshot when the explanation of the nav layout can suffice

2024-10-03 22:24 UTC, mikrdgz commented on docs/docusaurus/docs/reference/learn/data_quality_use_cases/dbt_tutorial.md
> +Copy the following code into the notebook. We recommend breaking up each part into different cells to see the outputs when you run each section. The overview of what we are doing here is creating a D
This section of the tutorial will demonstrate how to configure GX and create an Expectation. First you will create a Data Context to store your GX configuration and create a new Data Source (connecting to PostgreSQL). Next, you will create a Data Asset, defining a table to test with: the `customers` table in PostgreSQL. Then, you will create the Expectations `ExpectColumnValuesToNotBeNull` and `ExpectColumnValuesToBeBetween`. Finally, you will run Validations against the data. Copy the code into a new notebook, running each snippet in a separate cell.

2024-10-03 22:24 UTC, mikrdgz commented on docs/docusaurus/docs/reference/learn/data_quality_use_cases/dbt_tutorial.md
> +Start by naming the Notebook `customer_expectations.ipynb`, or a name of your choosing. Copy each of the following code blocks into separate cells in your notebook and run them one at a time using CT
Start by naming the Notebook `customer_expectations.ipynb`, or a name of your choosing. The following lines of code import the modules you will need to use GX and create a Data Context. This example stores the GX configuration to the file system.

2024-10-03 22:24 UTC, mikrdgz commented on docs/docusaurus/docs/reference/learn/data_quality_use_cases/dbt_tutorial.md
> +We first import a few modules that we’ll need to use in our GX configuration, as well as create the Data Context. In our example, we will store our configuration to the file system.
remove because this should be explained before the code as I rewrote above

2024-10-03 22:24 UTC, mikrdgz commented on docs/docusaurus/docs/reference/learn/data_quality_use_cases/dbt_tutorial.md
> +A Data Source is the GX representation of a data store. In this tutorial, we are using a PostgreSQL data source, but you can also connect to others, including Pandas, Snowflake and Databricks. A Data
Move this description up before the connection string code

2024-10-03 22:24 UTC, mikrdgz commented on docs/docusaurus/docs/reference/learn/data_quality_use_cases/dbt_tutorial.md
> +An Expectation Suite is a group of Expectations that describe how data should be tested. A Validation Definition simply links an Expectation Suite to the data it describes via the Batch Definition we
Generally move descriptions before the code as you were doing in the first half of the doc

2024-10-03 22:24 UTC, mikrdgz commented on docs/docusaurus/docs/reference/learn/data_quality_use_cases/dbt_tutorial.md
> +An Expectation Suite is a group of Expectations that describe how data should be tested. A Validation Definition simply links an Expectation Suite to the data it describes via the Batch Definition we
you can remove words like simply.

2024-10-03 22:24 UTC, mikrdgz commented on docs/docusaurus/docs/reference/learn/data_quality_use_cases/dbt_tutorial.md
> +An Expectation Suite is a group of Expectations that describe how data should be tested. A Validation Definition simply links an Expectation Suite to the data it describes via the Batch Definition we
Browse the [Expectations Gallery](https://greatexpectations.io/expectations/) to explore all available Expectations you can use to gain insight into your data.

2024-10-03 22:24 UTC, mikrdgz commented on docs/docusaurus/docs/reference/learn/data_quality_use_cases/dbt_tutorial.md
> +Open the data docs site here: [http://127.0.0.1:8888/edit/gx/uncommitted/data_docs/local_site/index.html](http://127.0.0.1:8888/edit/gx/uncommitted/data_docs/local_site/index.html)
View Validation results by navigating to the URL here: [http://127.0.0.1:8888/edit/gx/uncommitted/data_docs/local_site/index.html](http://127.0.0.1:8888/edit/gx/uncommitted/data_docs/local_site/index.html)

2024-10-03 22:24 UTC, mikrdgz commented on docs/docusaurus/docs/reference/learn/data_quality_use_cases/dbt_tutorial.md
> +Now you can view your Validation results.
rm

2024-10-03 22:24 UTC, mikrdgz commented on docs/docusaurus/docs/reference/learn/data_quality_use_cases/dbt_tutorial.md
> +You can see that the two Expectations that we have created are passing. Whenever Expectations fail, the status column will be updated to indicate a failure, along with the Observed Value column to in
You can see that the two Expectations you have created are passing. View failed Expectations in the status column. The Observed Value column displays any values that have fallen outside of the expected range.

2024-10-03 22:24 UTC, mikrdgz commented on docs/docusaurus/docs/reference/learn/data_quality_use_cases/dbt_tutorial.md
> +At this point we have verified that each service is working correctly so far. The last step is to now automate this process with a pipeline or dag in our workflow orchestration tool - Airflow. We wil
The final portion of this tutorial automates the process above with a pipeline or dag in the workflow orchestration tool Airflow. You will create a simple pipeline using the common write-audit-publish pattern.

2024-10-03 22:24 UTC, mikrdgz commented on docs/docusaurus/docs/reference/learn/data_quality_use_cases/dbt_tutorial.md
> +You can see that in this DAG file, we use the same commands that we executed manually earlier. The main point to note here is that executing a GX Checkpoint is as simple as loading the Data Context t
This dag file contains the process above, however executing the GX Checkpoint is as simple as loading the previously created Data Context and running the stored Checkpoint.

2024-10-03 22:24 UTC, mikrdgz commented on docs/docusaurus/docs/reference/learn/data_quality_use_cases/dbt_tutorial.md
> +It might take a few minutes for the new pipeline to show up in Airflow, but you will also see an error saying our dbt connection isn’t defined, so let’s create it now. We will also need to add the cr
After a few minutes, the new pipleline will appear in Airflow. Next, you will receive the following error:

{Insert the error here}

The next steps are to create a new dbt connection and add credentials for the PostgreSQL database.

2024-10-03 22:24 UTC, mikrdgz commented on docs/docusaurus/docs/reference/learn/data_quality_use_cases/dbt_tutorial.md
> +Run the DAG by clicking on the play button under Actions and then choosing Trigger DAG.
Run the DAG by navigating to **Actions** and clicking the **play button**. Then choose **Trigger DAG**.

you need to capitalize DAG everywhere because it's an acronym

2024-10-03 22:24 UTC, mikrdgz commented on docs/docusaurus/docs/reference/learn/data_quality_use_cases/dbt_tutorial.md
> +> Note: If you see an error saying “Task exited with return code Negsignal.SIGKILL” then it usually means that Airflow doesn’t have enough resources to run. Airflow recommends 4GB memory. Make sure y
put in a note

2024-10-03 22:24 UTC, mikrdgz commented on docs/docusaurus/docs/reference/learn/data_quality_use_cases/dbt_tutorial.md
> +Refresing the Data Docs page will show the new results from the DAG run:
Refresh the Data Docs page to see new results from the DAG run:

2024-10-03 22:24 UTC, mikrdgz commented on docs/docusaurus/docs/reference/learn/data_quality_use_cases/dbt_tutorial.md
> +If you are ready to take a step beyond what is covered here and collaborate with your team, be sure to check out [GX Cloud](https://greatexpectations.io/cloud), where you can use our online platform
If you are ready to take next steps and collaborate with your team using GX, check out GX Cloud, where you can use our online platform to run GX in a no-code environment and share results.

2024-10-03 22:24 UTC, mikrdgz commented on docs/docusaurus/docs/reference/learn/data_quality_use_cases/dbt_tutorial.md
> +Congratulations on completing this tutorial using PostgreSQL, dbt, GX and Airflow! By now, you should have an understanding of how to schedule and run data pipelines using some great open source tool
You have learned to build a pipeline using PostgreSQL, dbt, GX and Airflow. This tutorial covers a basic implementation for scheduling and running a data pipeline with open source tools. You can explore other possibilities with GX < maybe add a few examples here??> and connect you own data sources. See our Expectation Gallery to learn about all the Expectations you can run on your data.

2024-10-03 22:44 UTC, r34ctor commented on docs/docusaurus/docs/reference/learn/data_quality_use_cases/dbt_tutorial.md
> +This tutorial will enable you to schedule and run data pipelines locally using PostgreSQL as the database, dbt for transforming data, Great Expectations for data quality and Airflow for workflow orch
Thanks for pointing this out! I've updated the tutorial to address this.

2024-10-04 21:33 UTC, jtimberman requested changes

2024-10-04 21:33 UTC, jtimberman commented on docs/docusaurus/docs/reference/learn/integrations/dbt_tutorial.md
> +dpt deps
`s/dpt/dbt/` here

2024-10-07 14:56 UTC, mikrdgz commented on docs/docusaurus/docs/reference/learn/integrations/dbt_tutorial.md
> +docker exec great-expectations jupyter notebook --allow-root --no-browser --ip=0.0.0.0
I think you need to instruct them to install jupyter first or this command won't work

2024-10-07 14:58 UTC, r34ctor commented on docs/docusaurus/docs/reference/learn/integrations/dbt_tutorial.md
> +docker exec great-expectations jupyter notebook --allow-root --no-browser --ip=0.0.0.0
Jupyter should have been installed in GX Docker container.

2024-10-07 15:08 UTC, mikrdgz commented on docs/docusaurus/docs/reference/learn/integrations/dbt_tutorial.md
> +In the next section of this tutorial, you will follow the [Getting Started](https://docs.greatexpectations.io/docs/oss/get_started/get_started_with_gx_and_sql) guide to run GX with SQL within a Docke
This link 404s

2024-10-07 15:35 UTC, jtimberman approved these changes

2024-10-07 15:45 UTC, jtimberman commented
@cla-bot check

2024-10-07 17:11 UTC, merged

2024-10-08 16:02 UTC, mikrdgz commented on docs/docusaurus/docs/reference/learn/integrations/dbt_tutorial.md
> +In addition to the prerequisites below, you are recommneded to use an IDE like VSCode to organize your project.
Typo