[DOCS] WIP: Fix broken links
great-expectations/great_expectations pull request #10541
Opened 2024-10-18 21:14 UTC by deborahniesz

- [ ] Description of PR changes above includes a link to [an existing GitHub issue](https://github.com/great-expectations/great_expectations/issues)
- [ ] PR title is prefixed with one of: [BUGFIX], [FEATURE], [DOCS], [MAINTENANCE], [CONTRIB]
- [ ] Code is linted - run `invoke lint` (uses `ruff format` + `ruff check`)
- [ ] Appropriate tests and docs have been updated

For more information about contributing, see [Contribute](https://docs.greatexpectations.io/docs/contributing/contributing_checklist).

After you submit your PR, keep the page open and **monitor the statuses of the various checks made by our continuous integration process at the bottom of the page. Please fix any issues that come up** and [reach out on Slack](https://greatexpectations.io/slack) if you need help. Thanks for contributing!

2024-10-21 22:20 UTC, josectobar commented on docs/docusaurus/docs/reference/learn/data_quality_use_cases/missingness.md
> +This article assumes basic familiarity with GX components and workflows. If you're new to GX, start with the [GX Overview](/cloud/overview/gx_cloud_overview.md) to familiarize yourself with key conce
Why is this not an absolute URL path? `https://docs.greatexpectations.io/docs/cloud/overview/gx_cloud_overview`

2024-10-21 22:22 UTC, josectobar requested changes
It looks great, I have one question.

2024-10-22 04:04 UTC, joshzzheng commented on docs/docusaurus/versioned_docs/version-0.18/reference/learn/terms/data_context.md
> +For production deployments, you will want to define these components according to your Data Source and production environment. This may include storing information about those components in something
Link here: https://greatexpectations.io/integrations

2024-10-22 15:18 UTC, deborahniesz commented on docs/docusaurus/docs/reference/learn/data_quality_use_cases/missingness.md
> +This article assumes basic familiarity with GX components and workflows. If you're new to GX, start with the [GX Overview](/cloud/overview/gx_cloud_overview.md) to familiarize yourself with key conce
to be honest I saw that other liks where written like that and I just assumed it was the convention used, I didn't realize the previous overview link was absolute :sweat_smile: 

https://github.com/great-expectations/great_expectations/blob/6c837562a9f63b5127f336308585eaf158a60fe4/docs/docusaurus/docs/reference/learn/data_quality_use_cases/missingness.md?plain=1#L63-L71

But you are right, I'll change it right away :saluting_face:

2024-10-22 15:39 UTC, joshzzheng approved these changes

2024-10-22 17:15 UTC, josectobar approved these changes

2024-10-22 17:47 UTC, merged