[BUGFIX] ExpectationSuiteValidationResult should contain checkpoint_name
great-expectations/great_expectations pull request #10645
Opened 2024-11-08 03:25 UTC by TrangPham

In V1, a checkpoint cannot be looked up by ID and ran, instead you need to use the name. 

ExpectationSuiteValidationResultMeta shows that checkpoint_name should be available but it is not. This PR rectifies that.
https://github.com/great-expectations/great_expectations/blob/d4b8c189121dc565c4aeb50c6c58f5ce4345baa3/great_expectations/core/expectation_validation_result.py#L399-L405

A separate discussion needs to be had if checkpoint_id should be used for looking up and running checkpoints instead of checkpoint_name.

Here are some related PRs for context:
- https://github.com/great-expectations/great_expectations/pull/10169

- [ ] Description of PR changes above includes a link to [an existing GitHub issue](https://github.com/great-expectations/great_expectations/issues)
- [ ] PR title is prefixed with one of: [BUGFIX], [FEATURE], [DOCS], [MAINTENANCE], [CONTRIB]
- [ ] Code is linted - run `invoke lint` (uses `ruff format` + `ruff check`)
- [ ] Appropriate tests and docs have been updated

For more information about contributing, visit our [community resources](https://docs.greatexpectations.io/docs/core/introduction/community_resources#contribute-code-or-documentation).

After you submit your PR, keep the page open and **monitor the statuses of the various checks made by our continuous integration process at the bottom of the page. Please fix any issues that come up** and [reach out on Slack](https://greatexpectations.io/slack) if you need help. Thanks for contributing!

2024-11-08 03:26 UTC, TrangPham commented on great_expectations/checkpoint/checkpoint.py
> +            result.meta["checkpoint_name"] = self.name
Note that within another PR it was noted that perhaps the logic here should be removed. https://github.com/great-expectations/great_expectations/pull/10169 in favor of passing checkpoint_id down to the location which creates the result such the creation is all done in one place.

2024-11-08 23:55 UTC, anthonyburdi approved these changes
LGTM - One non-blocking question.

2024-11-08 23:55 UTC, anthonyburdi commented on great_expectations/core/validation_definition.py
> +        checkpoint_name: Optional[str] = None,
Do we need to do a minor version bump for changing the public api or is it ok to do in a patch release because it is optional?

2024-11-08 23:58 UTC, TrangPham commented on great_expectations/core/validation_definition.py
> +        checkpoint_name: Optional[str] = None,
@billdirks what do you think?

To me, this does not require it as we aren't change the ExpectationSuiteValidationResultMeta class. Checkpoint_name was already a field on it.

2024-11-12 13:20 UTC, joshua-stauffer requested changes
I'm putting a block on this so timber can have a chance to review at our sync today. The implementation looks fine, but blocking because we explicitly decided to remove the `checkpoint_name` parameter from the `Checkpoint.run` signature and `meta`. I do think there may be other approaches to solve this problem, which might actually end up being better for users in the long run.

2024-11-12 20:12 UTC, joshua-stauffer commented
hey @TrangPham , i brought this to the team, and there's consensus that updating the public API of `ValidationResult.run` and putting `checkpoint_name` back into `meta` isn't in line with our longer term goals. As such, I'd recommend closing this PR. If you have questions, disagree, or want to discuss more, i'm happy to put some time on the calendar to sync 👍 

Per our conversations in [jira](https://greatexpectations.atlassian.net/browse/ZELDA-1086?focusedCommentId=21828) and [slack](https://greatexpectationslabs.slack.com/archives/C05V0M18TEJ/p1730811080213879?thread_ts=1730765983.400089&cid=C05V0M18TEJ), I'd recommend you get the checkpoint name at the graphql layer. Happy to pair if you decide to go with that approach and have questions!

2024-11-14 01:21 UTC, closed without merging