[FEATURE] Migration of Expectations to Atomic Prescriptive Renderers part 2
great-expectations/great_expectations pull request #3537
Opened 2021-10-12 20:56 UTC by Shinnnyshinshin

Changes proposed in this pull request:

- Migration of Prescriptive Renderers to Atomic Prescriptive Renderers
- Migration of logic from _prescriptive_renderer() to _atomic_prescriptive_template().
- Add json-schema for parameters in params_with_json_schema
- This is part 2 of 2 PRs that will do the Migration of Expectations to Atomic Prescriptive Renderers

Previous Design Review notes:
-
-
-

### Definition of Done
Please delete options that are not relevant.

- [x] My code follows the Great Expectations [style guide](https://docs.greatexpectations.io/en/latest/contributing/style_guide.html?highlight=style%20guide)
- [x] I have performed a [self-review](https://docs.greatexpectations.io/en/latest/contributing/contribution_checklist.html?highlight=checklist) of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have run any local integration tests and made sure that nothing is broken.

Thank you for submitting!

2021-10-17 20:41 UTC, Shinnnyshinshin commented
re-opening for clean up

2021-10-20 23:00 UTC, roblim requested changes
Everything looks good except for those expectations with calls to  `add_value_set_params` in `_atomic_prescriptive_template` - see comments.

2021-10-20 23:00 UTC, roblim commented on great_expectations/expectations/core/expect_column_values_to_be_in_type_list.py
> +
If we want to re-use `add_value_set_params` util function here, the function will have to be updated (and probably re-named to something more general) since the underlying logic is built to handle a `params` dict with `value_set` key (and this expectation has no such key, but an analogous key `types_list`.

2021-10-20 23:00 UTC, roblim commented on great_expectations/expectations/core/expect_column_values_to_be_in_type_list.py
> +
(I'm assuming that since the call is here, the original intent was to have the elements in `type_list` be converted into dicts with schema info, just like all the set expectations)

2021-10-20 23:00 UTC, roblim commented on great_expectations/expectations/core/expect_column_values_to_match_regex_list.py
> +
See comment above for `expect_column_values_to_be_in_type_list`. `add_value_set_params` expects a `value_set` key, but this expectation doesn't have such a key (analogous key here is `regex_list`)

2021-10-20 23:00 UTC, roblim commented on great_expectations/expectations/core/expect_column_values_to_not_match_regex_list.py
> +        return (template_str, params_with_json_schema, styling)
See above comments around updating `add_value_set_params`.

2021-10-20 23:00 UTC, roblim commented on great_expectations/expectations/core/expect_multicolumn_values_to_be_unique.py
> +        return (template_str, params_with_json_schema, styling)
See above comments on updating `add_value_set_params`

2021-10-20 23:00 UTC, roblim commented on great_expectations/expectations/core/expect_select_column_values_to_be_unique_within_record.py
> +
See above comments.

2021-10-20 23:00 UTC, roblim commented on great_expectations/expectations/core/expect_table_columns_to_match_ordered_list.py
> +        return (template_str, params_with_json_schema, styling)
See above comments

2021-10-21 15:43 UTC, roblim approved these changes

2021-10-21 15:55 UTC, merged