[CONTRIB][MAINTENANCE] Custom query expectation and editing query.template_values metric
great-expectations/great_expectations pull request #7390
Opened 2023-03-17 10:09 UTC by mantasmy

Changes proposed in this pull request:
- add new expectation **expect_queried_custom_query_results_to_be_custom**. Custom query can be passed as user_query inside template_dict using **query.template_values** metric and tested if output count matches the value.
```
"template_dict": {
                 "user_query": "select * from active_batch"
                 },
"value": 0
```
- adjust **query.template_values**. Overwriting active_batch inside dict was added.

2023-03-17 11:20 UTC, mantasmy commented
@cla-bot check

2023-03-21 17:42 UTC, kenwade4 requested changes
Thanks for contributing this new Expectation @mantasmy! There are some minor changes requested (to allow more backends to work with this Expectation).

In addition to the changes requested by line number, here's a bonus for postgresql support

```
sqlalchemy.exc.ProgrammingError: (psycopg2.errors.SyntaxError) subquery in FROM must have an alias
LINE 3:             from (select * from test)
                         ^
HINT:  For example, FROM (SELECT ...) [AS] foo.

[SQL:
            select count(1)
            from (select * from test)
            ]
(Background on this error at: https://sqlalche.me/e/14/f405)
```

It's possible that adding an alias will also not break the backends that this Expectation is currently working with (sqlite, bigquery, redshift, snowflake). What do you think @itaise?

2023-03-21 17:42 UTC, kenwade4 commented on contrib/experimental/great_expectations_experimental/expectations/expect_queried_custom_query_to_return_num_rows.py
> +            "tests": [
At the same nesting level as tests, add `"only_for": ["sqlite", "bigquery", "redshift", "snowflake"],`

2023-03-21 17:42 UTC, kenwade4 commented on contrib/experimental/great_expectations_experimental/expectations/expect_queried_custom_query_to_return_num_rows.py
> +                    "only_for": ["sqlite"],
Delete this `only_for` line

2023-03-21 17:42 UTC, kenwade4 commented on contrib/experimental/great_expectations_experimental/expectations/expect_queried_custom_query_to_return_num_rows.py
> +                    "only_for": ["sqlite"],
Delete this `only_for` line

2023-03-21 17:42 UTC, kenwade4 commented on contrib/experimental/great_expectations_experimental/expectations/expect_queried_custom_query_to_return_num_rows.py
> +                    "data": {"col1": [1, 2, 3, 4, 5, 5], "col2": ["10", 3, 4, 4, 5, 5]},
Consider changing the `"10"` to `10`. Spark fails with `TypeError("field col2: Can not merge type <class 'pyspark.sql.types.StringType'> and <class 'pyspark.sql.types.LongType'>")` when trying to get a test validator.

Ditto for Trino `ProgrammingError('(trino.exceptions.TrinoUserError) TrinoUserError(type=USER_ERROR, name=TYPE_MISMATCH, message="line 2:2: Values rows have mismatched types: row(integer, varchar(2)) vs row(integer, integer)", query_id=20230321_152044_00366_yc6mi)')`

2023-03-22 06:08 UTC, mantasmy commented
@kenwade4 Thanks! Did adjustments as requested. 
In regards of alias. I have added it for now and tested in Snowflake - it works well. Not sure about rest the backends.
But @itaise has special handling for alias in **query_temp_values.py** (metric) @ line 82. So maybe it won't work well for all of the backends?

2023-03-22 19:07 UTC, kenwade4 approved these changes
Good stuff. The alias change and removing quotes from that number in sample data worked (postgresql and trino)

2023-03-23 08:28 UTC, merged

2023-03-23 15:52 UTC, kenwade4 commented
@mantasmy you may want to try to get spark working and submit a separate PR in the future. Thanks again.