[DOCS] Remove, relocate, consolidate and edit Contributing content
great-expectations/great_expectations pull request #7669
Opened 2023-04-20 18:27 UTC by kwcanuck

### What is the issue?

Currently, there is a _[Contributing](https://docs.greatexpectations.io/docs/contributing/contributing)_ section in the Great Expectations help. When I started reviewing this content, I noticed information was duplicated, content was out of date, and the organizational structure was confusing. In addition, research and analysis indicates that this type of content is typically provided in GitHub repositories and not within product help. 

### What was done?

- Consolidation of the code contribution process into a single document named _[Contribute a code change](https://github.com/great-expectations/great_expectations/blob/contributing-and-style-readme/CONTRIBUTING_CODE.md)_

- Consolidation of the package contribution process into a single document named _[Contribute packages](https://github.com/great-expectations/great_expectations/blob/contributing-and-style-readme/CONTRIBUTING_PACKAGES.md)_

- Consolidation of the Expectation contribution process into a single document named _[Contribute custom Expectations](https://github.com/great-expectations/great_expectations/blob/contributing-and-style-readme/CONTRIBUTING_EXPECTATIONS.md)_ 

- Consolidation of the documentation contribution process into a single document titled _[Contribute to Great Expectations documentation](https://github.com/great-expectations/great_expectations/tree/contributing-and-style-readme/docs)_

- Removing the topics used to create the new  _Contribute a code change_, _Contribute packages_, and _Contribute custom Expectations_ topics from the existing TOC 

- Removing the topics used to create the new _Contribute to Great Expectations documentation_ from the existing TOC

- Creating a new README for the _Contribute to Great Expectations documentation_ content and adding the README to the docs repository so it is the first item users see

- Adding the content from the How to write a how-to-guide and How to write integration documentation topics to  _Contribute to Great Expectations documentation_ 

- Creating a new `template` folder in the docs repository and adding the how-to and integration templates

- Renaming the existing _Levels of Maturity_ topic  _Feature and code readiness_ and moving the topic to the _Reference_ section

- Performing an initial edit of all content and correcting style, grammar, and consistency issues

- Removing the existing _Contributions_ section from the TOC

CC: @joshzzheng

2023-04-25 18:25 UTC, joshzzheng approved these changes

2023-04-25 19:31 UTC, tjholsman requested changes
This change removes most of the existing Contributing sidebar in the docs but it does not remove all of the docs themselves. Is that intended?

One related example, [Creating custom expectations](https://deploy-preview-7669--niobium-lead-7998.netlify.app/docs/guides/expectations/creating_custom_expectations/overview) has a link near the end to [How to contribute a custom expectation]9https://deploy-preview-7669--niobium-lead-7998.netlify.app/docs/guides/expectations/contributing/how_to_contribute_a_custom_expectation_to_great_expectations), which has been removed from sidebar but not removed from the docs in this PR. This renders a standalone docs page with no sidebar. Should this be updated to point to the new Github page CONTRIBUTING_EXPECTATIONS?

2023-04-25 20:30 UTC, kwcanuck commented
@tjholsman you are correct. This PR removes the Contributing section (Sidebar) entirely. I have not deleted the individual topics as I wasn't sure if this PR would be approved as submitted. If a reviewer requested that an original topic be returned to the TOC, it would be a quick fix if the topic was still available. I'll remove the topics that are no longer used when the PR is approved. 

I'll also be correcting any links and/or adding a redirect for any topics that are removed. It's all part of the final clean up before pushing the changes. Again, I didn't want to go too far in case my changes were not accepted as submitted. 

For your reference, here are the redirects:

![image](https://user-images.githubusercontent.com/104205257/234628344-2a630f0b-e141-4f6c-8547-e2e3eae3b433.png)

Here is the commit that removed the unused topics:

![image](https://user-images.githubusercontent.com/104205257/234628810-4b59a36a-a990-420c-9c8d-164de3a23b10.png)

2023-04-26 20:27 UTC, tjholsman approved these changes
lgtm - thanks, @kwcanuck!

2023-04-27 13:09 UTC, Rachel-Reverie commented on docs/docusaurus/sidebars.js
> -            { type: 'doc', id: 'reference/usage_statistics' }
Relocating this may require approval from outside of DevRel.

2023-04-27 13:34 UTC, Rachel-Reverie approved these changes

2023-04-27 13:34 UTC, Rachel-Reverie commented on docs/docusaurus/static/_redirects
> +/docs/contributing/contributing_test /ghttps://github.com/great-expectations/great_expectations/blob/contributing-and-style-readme/CONTRIBUTING_CODE.md
```suggestion
/docs/contributing/contributing_test /https://github.com/great-expectations/great_expectations/blob/contributing-and-style-readme/CONTRIBUTING_CODE.md
```
Pretty sure that extra `g` was a typo.

2023-04-27 13:34 UTC, Rachel-Reverie commented on docs/docusaurus/docs/templates/how_to_template.md
> +import Prerequisites from '/docs/guides/connecting_to_your_data/components/prerequisites.jsx'
```suggestion
import Prerequisites from '/docs/components/_prerequisites.jsx'
```
This is an old link.  We're trying to consolidate "universal" components like this in `/docs/components/` so we can more easily update formatting for them.

The same applies to the "NextSteps" import, except that I don't believe we have an updated version in `/docs/components/` yet.

2023-04-27 13:34 UTC, Rachel-Reverie commented on docs/docusaurus/static/_redirects
> +/docs/contributing/contributing_github /docs/README
I tested this redirect in the netlify preview and it does not appear to be working.

2023-04-27 16:21 UTC, austiezr requested changes
1 necessary fix re: installing from the repo.

Other changes align with previous convention but not strongly held and won't gate.

2023-04-27 16:21 UTC, austiezr commented on docs/docusaurus/docs/guides/expectations/creating_custom_expectations/how_to_create_custom_column_aggregate_expectations.md
> +This guide will leave you with a Custom Expectation sufficient for contribution to Great Expectations at an Experimental level.
```suggestion
This guide will leave you with a Custom Expectation sufficient for [contribution](https://github.com/great-expectations/great_expectations/blob/contributing-and-style-readme/CONTRIBUTING_EXPECTATIONS.md) to Great Expectations at an Experimental level.
```

2023-04-27 16:21 UTC, austiezr commented on CONTRIBUTING_CODE.md
> +pip install -e
```suggestion
pip install -e .
```

2023-04-27 16:21 UTC, austiezr commented on CONTRIBUTING_CODE.md
> +pip install -e
May be worth noting that this must be run from the root of the GX repo; not a strongly held opinion though.

2023-04-27 16:21 UTC, austiezr commented on CONTRIBUTING_EXPECTATIONS.md
> +To submit a custom Expectation to Great Expectations for consideration, you complete the following tasks:
```suggestion
To submit a Custom Expectation to Great Expectations for consideration, you complete the following tasks:
```

2023-04-27 16:21 UTC, austiezr commented on CONTRIBUTING_EXPECTATIONS.md
> +- A custom Expectation. See [Creating Custom Expectations](https://docs.greatexpectations.io/docs/guides/expectations/creating_custom_expectations/overview/).
```suggestion
- A Custom Expectation. See [Creating Custom Expectations](https://docs.greatexpectations.io/docs/guides/expectations/creating_custom_expectations/overview/).
```

2023-04-27 16:21 UTC, austiezr commented on CONTRIBUTING_EXPECTATIONS.md
> +Before you submit your custom Expectation, you need to verify it meets the submission requirements. Great Expectations provides a checklist to help you determine if your custom Expectation meets the
```suggestion
Before you submit your Custom Expectation, you need to verify it meets the submission requirements. Great Expectations provides a checklist to help you determine if your Custom Expectation meets the minimum requirements. Your Custom Expectation must meet the first five of the listed requirements to qualify for submission.
```

2023-04-27 16:21 UTC, austiezr commented on CONTRIBUTING_EXPECTATIONS.md
> +To generate the Expectation checklist, add the `print_diagnostic_checklist()` instance method to your custom Expectation. When the instance method runs, it returns results similar to the following:
```suggestion
To generate the Expectation checklist, add the `print_diagnostic_checklist()` instance method to your Custom Expectation. When the instance method runs, it returns results similar to the following:
```

2023-04-27 16:21 UTC, austiezr commented on CONTRIBUTING_EXPECTATIONS.md
> +Verifying your custom Expectation metadata ensures that it is accredited to you and includes an accurate description.
```suggestion
Verifying your Custom Expectation metadata ensures that it is accredited to you and includes an accurate description.
```

2023-04-27 16:21 UTC, austiezr commented on CONTRIBUTING_EXPECTATIONS.md
> +Great Expectations maintains a number of custom Expectation packages, that contain thematically related custom Expectations. These packages are located in the [Great Expectations contrib directory](h
```suggestion
Great Expectations maintains a number of Custom Expectation packages, that contain thematically related Custom Expectations. These packages are located in the [Great Expectations contrib directory](https://github.com/great-expectations/great_expectations/tree/develop/contrib) and on [PyPI](https://pypi.org/).
```

2023-04-27 16:21 UTC, austiezr commented on CONTRIBUTING_EXPECTATIONS.md
> +If your custom Expectation fits within one of these packages, you're encouraged to contribute your custom Expectation directly to one of these packages.
```suggestion
If your Custom Expectation fits within one of these packages, you're encouraged to contribute your Custom Expectation directly to one of these packages.
```

2023-04-27 16:21 UTC, austiezr commented on CONTRIBUTING_EXPECTATIONS.md
> +Confirm the `library_metadata` object for your custom Expectation includes the following information:
```suggestion
Confirm the `library_metadata` object for your Custom Expectation includes the following information:
```

2023-04-27 16:21 UTC, austiezr commented on CONTRIBUTING_EXPECTATIONS.md
> +If you're not contributing to a specific package, your Custom Expectation is automatically published in the [PyPI great-expectations-experimental package](https://pypi.org/project/great-expectations-
```suggestion
If you're not contributing to a specific package, your Custom Expectation is automatically published in the [PyPI great-expectations-experimental package](https://pypi.org/project/great-expectations-experimental/). This package contains all Great Expectations experimental community-contributed Custom Expectations that have not been submitted to other packages.
```

2023-04-27 16:21 UTC, austiezr commented on CONTRIBUTING_EXPECTATIONS.md
> +- `requirements`: Identifies if your custom Expectation relies on third-party packages.
```suggestion
- `contributors`: Identifies the creators of the Custom Expectation.
- `tags`: Identifies the Custom Expectation functionality and domain. For example, `statistics`, `flexible comparisons`, `geography`, and so on.
- `requirements`: Identifies if your Custom Expectation relies on third-party packages.
```

2023-04-27 16:21 UTC, austiezr commented on CONTRIBUTING_EXPECTATIONS.md
> +    - [CONTRIB] for the contribution of custom Expectations and supporting work into the `contrib/` directory.
```suggestion
    - [CONTRIB] for the contribution of Custom Expectations and supporting work into the `contrib/` directory.
```

2023-04-27 16:21 UTC, austiezr commented on CONTRIBUTING_CODE.md
> +To create and submit a custom Expectation to Great Expectations for consideration, see [CONTRIBUTING_EXPECTATIONS](https://github.com/great-expectations/great_expectations/blob/contributing-and-style
```suggestion
To create and submit a Custom Expectation to Great Expectations for consideration, see [CONTRIBUTING_EXPECTATIONS](https://github.com/great-expectations/great_expectations/blob/contributing-and-style-readme/CONTRIBUTING_EXPECTATIONS.md) in the `great_expectations` repository.
```

2023-04-27 16:21 UTC, austiezr commented on CONTRIBUTING_CODE.md
> +Python dependencies are required to modify Great Expectations code, submit a new feature, or submit a custom Expectation.
```suggestion
Python dependencies are required to modify Great Expectations code, submit a new feature, or submit a Custom Expectation. 
```

2023-04-27 16:21 UTC, austiezr commented on CONTRIBUTING_CODE.md
> +    - [CONTRIB] for the contribution of custom Expectations and supporting work into the `contrib/` directory.
```suggestion
    - [CONTRIB] for the contribution of Custom Expectations and supporting work into the `contrib/` directory.
```

2023-04-27 16:21 UTC, austiezr commented on CONTRIBUTING_EXPECTATIONS.md
> +# Contribute custom Expectations
```suggestion
# Contribute Custom Expectations
```

2023-04-27 16:21 UTC, austiezr commented on CONTRIBUTING_EXPECTATIONS.md
> +    If your custom Expectation doesn't meet the minimum requirements in the validation checklist, it is failing testing, or there is a functionality error, you'll be asked to resolve the issues befor
```suggestion
    If your Custom Expectation doesn't meet the minimum requirements in the validation checklist, it is failing testing, or there is a functionality error, you'll be asked to resolve the issues before your Custom Expectation can move forward.
```

2023-04-27 16:21 UTC, austiezr commented on CONTRIBUTING_EXPECTATIONS.md
> +    If you are submitting a production custom Expectation, Great Expectations requires that your custom Expectation meet or exceed Great Expectation standards for testing and coding.
```suggestion
    If you are submitting a production Custom Expectation, Great Expectations requires that your Custom Expectation meet or exceed Great Expectation standards for testing and coding.
```

2023-04-27 16:21 UTC, austiezr commented on docs/docusaurus/docs/contributing/contributing_overview.md
> +- To create and submit a custom Expectation to Great Expectations for consideration, see [CONTRIBUTING_EXPECTATIONS](https://github.com/great-expectations/great_expectations/blob/contributing-and-sty
```suggestion
- To create and submit a Custom Expectation to Great Expectations for consideration, see [CONTRIBUTING_EXPECTATIONS](https://github.com/great-expectations/great_expectations/blob/contributing-and-style-readme/CONTRIBUTING_EXPECTATIONS.md) in the `great_expectations` repository.
```

2023-04-27 16:21 UTC, austiezr commented on CONTRIBUTING_EXPECTATIONS.md
> +    When your custom Expectation has successfully passed testing and received approval from a code owner, your contribution is complete. Your custom Expectation will be included in the next release o
```suggestion
    When your Custom Expectation has successfully passed testing and received approval from a code owner, your contribution is complete. Your custom Expectation will be included in the next release of Great Expectations and an announcement will appear in the release notes
```

2023-04-27 16:21 UTC, austiezr commented on CONTRIBUTING_PACKAGES.md
> +- A custom Expectation. See [Creating Custom Expectations](https://docs.greatexpectations.io/docs/guides/expectations/creating_custom_expectations/overview/).
```suggestion
- A Custom Expectation. See [Creating Custom Expectations](https://docs.greatexpectations.io/docs/guides/expectations/creating_custom_expectations/overview/).
```

2023-04-27 16:21 UTC, austiezr commented on CONTRIBUTING_PACKAGES.md
> +To create and submit a custom Expectation to Great Expectations for consideration, see [CONTRIBUTING_EXPECTATIONS](https://github.com/great-expectations/great_expectations/blob/contributing-and-style
```suggestion
To create and submit a Custom Expectation to Great Expectations for consideration, see [CONTRIBUTING_EXPECTATIONS](https://github.com/great-expectations/great_expectations/blob/contributing-and-style-readme/CONTRIBUTING_EXPECTATIONS.md) in the `great_expectations` repository.
```

2023-04-27 17:44 UTC, austiezr approved these changes
🚀

2023-04-28 12:20 UTC, merged