Add CLI warnings for fluent datasources
great-expectations/great_expectations pull request #7685
Opened 2023-04-21 15:49 UTC by dctalbot

Please annotate your PR title to describe what the PR does, then give a brief bulleted description of your PR below. PR titles should begin with [BUGFIX], [FEATURE], [DOCS], [MAINTENANCE], or [CONTRIB]. If a new feature introduces breaking changes for the Great Expectations API or configuration files, please also add [BREAKING]. You can read about the tags in our [contributor checklist](https://docs.greatexpectations.io/docs/contributing/contributing_checklist).

Changes proposed in this pull request:
-
-
-

After submitting your PR, CI checks will run and @cla-bot will check for your CLA signature.

For a PR with nontrivial changes, we review with both design-centric and code-centric lenses.

In a design review, we aim to ensure that the PR is consistent with our relationship to the open source community, with our software architecture and abstractions, and with our users' needs and expectations. That review often starts well before a PR, for example in GitHub issues or Slack, so please link to relevant conversations in notes below to help reviewers understand and approve your PR more quickly (e.g. `closes #123`).

Previous Design Review notes:
-
-
-

### Definition of Done
Please delete options that are not relevant.

- [ ] My code follows the Great Expectations [style guide](https://docs.greatexpectations.io/docs/contributing/style_guides/code_style)
- [ ] I have performed a [self-review](https://docs.greatexpectations.io/docs/contributing/contributing_checklist) of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added [unit tests](https://docs.greatexpectations.io/docs/contributing/contributing_test#writing-unit-and-integration-tests) where applicable and made sure that new and existing tests are passing.
- [ ] I have run any local integration tests and made sure that nothing is broken.

Thank you for submitting!

2023-04-21 17:49 UTC, Kilo59 approved these changes

2023-04-21 17:51 UTC, anthonyburdi requested changes
Hi @dctalbot! Thanks for this change. Would you mind also adding some tests to `tests/cli/test_checkpoint.py` for the different cases? Thank you! Happy to pair if helpful.

2023-04-24 22:24 UTC, anthonyburdi approved these changes
Thanks for adding the tests!

2023-04-24 22:24 UTC, anthonyburdi commented on tests/cli/test_checkpoint.py
> +    The `checkpoint new` CLI flow should now print warnings/errors if all of the Datasources in the DataContext are configured with the block config style API.
Sorry for the nit, just confused me the first time I read it.
```suggestion
    The `checkpoint new` CLI flow should not print warnings/errors if all of the Datasources in the DataContext are configured with the block config style API.
```

2023-04-26 03:01 UTC, merged