[DOCS] Updating cross-table comparison guide with Fluent Datasources
great-expectations/great_expectations pull request #7691
Opened 2023-04-21 18:16 UTC by austiezr

Please annotate your PR title to describe what the PR does, then give a brief bulleted description of your PR below. PR titles should begin with [BUGFIX], [FEATURE], [DOCS], [MAINTENANCE], or [CONTRIB]. If a new feature introduces breaking changes for the Great Expectations API or configuration files, please also add [BREAKING]. You can read about the tags in our [contributor checklist](https://docs.greatexpectations.io/docs/contributing/contributing_checklist).

Changes proposed in this pull request:
- Converts guide to using Fluent Datasources & the OnboardingDataAssistant

After submitting your PR, CI checks will run and @cla-bot will check for your CLA signature.

For a PR with nontrivial changes, we review with both design-centric and code-centric lenses.

In a design review, we aim to ensure that the PR is consistent with our relationship to the open source community, with our software architecture and abstractions, and with our users' needs and expectations. That review often starts well before a PR, for example in GitHub issues or Slack, so please link to relevant conversations in notes below to help reviewers understand and approve your PR more quickly (e.g. `closes #123`).

Previous Design Review notes:
-
-
-

### Definition of Done
Please delete options that are not relevant.

- [ ] My code follows the Great Expectations [style guide](https://docs.greatexpectations.io/docs/contributing/style_guides/code_style)
- [ ] I have performed a [self-review](https://docs.greatexpectations.io/docs/contributing/contributing_checklist) of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added [unit tests](https://docs.greatexpectations.io/docs/contributing/contributing_test#writing-unit-and-integration-tests) where applicable and made sure that new and existing tests are passing.
- [ ] I have run any local integration tests and made sure that nothing is broken.

Thank you for submitting!

2023-04-25 16:02 UTC, anthonyburdi requested changes
Looks great! Just a couple tweaks. Happy to discuss / pair if helpful!

2023-04-25 16:02 UTC, anthonyburdi commented on tests/integration/docusaurus/expectations/advanced/data_assistant_cross_table_comparison.py
> +).build_batch_request()
What do you think about showing the creation of the datasources in these snippets where we get a batch request? Otherwise someone has to jump between a few different docs to get this set up.

2023-04-25 16:02 UTC, anthonyburdi commented on tests/integration/test_definitions/multiple_backend/integration_tests.py
>      IntegrationTestFixture(
Strange, looks like this IntegrationTestFixture test definition is in here twice? What do you think about removing this one and leaving the one above in `cross_table_comparisons`?

2023-04-25 16:02 UTC, anthonyburdi commented on tests/integration/test_definitions/multiple_backend/integration_tests.py
> +        user_flow_script="tests/integration/docusaurus/expectations/advanced/data_assistant_cross_table_comparison.py",
Since this is using two backends, we will need to add a new job (currently, just until `docs_integration` tests are working again). Something like https://github.com/great-expectations/great_expectations/pull/7717/files#diff-8122d09374920cf7c64d1a6ae4ced459d2d631e111612d3ba5b5d091371739f0 but with mysql and postgres. Happy to pair - let me know!

2023-04-25 19:48 UTC, austiezr commented on tests/integration/docusaurus/expectations/advanced/data_assistant_cross_table_comparison.py
> +).build_batch_request()
I'm hesitant to reproduce entire datasource config docs within this one; given that its under the `advanced skills` bucket, I would say the onus is on a reader to have already created datasources. I think it's reasonable to link to a datasource config guide in the pre-reqs though! Happy to be rebuffed on this.

2023-04-25 19:49 UTC, austiezr commented on tests/integration/test_definitions/multiple_backend/integration_tests.py
>      IntegrationTestFixture(
*LOVE* that.

2023-04-26 13:39 UTC, anthonyburdi commented on tests/integration/docusaurus/expectations/advanced/data_assistant_cross_table_comparison.py
> +).build_batch_request()
Very fair point. And an easy tweak to add if users have questions about this doc. I'm fine leaving as-is. Thanks for the explanation!

2023-04-26 13:44 UTC, anthonyburdi commented on ci/azure-pipelines-dev.yml
> +          mysql: mysql
I'm seeing a test failure - take a look at the mysql stage in this file starting on [line 462](https://github.com/great-expectations/great_expectations/pull/7691/files#diff-8122d09374920cf7c64d1a6ae4ced459d2d631e111612d3ba5b5d091371739f0R462), there are a few other items that are needed to get the database set up, namely [lines 480 thru 491](https://github.com/great-expectations/great_expectations/pull/7691/files#diff-8122d09374920cf7c64d1a6ae4ced459d2d631e111612d3ba5b5d091371739f0R480-R491).

2023-04-26 13:45 UTC, anthonyburdi commented on ci/azure-pipelines-dev.yml
> +
```suggestion

          - script: |
              printf 'Waiting for MySQL database to accept connections'
              until mysql --host=localhost --protocol=TCP --port=3306 --user=root --password='' --execute "SHOW DATABASES"; do
                printf '.'
                sleep 1;
              done;
            displayName: Wait for database to initialise
          - script: |
              echo "SET GLOBAL sql_mode=(SELECT REPLACE(@@sql_mode,'ONLY_FULL_GROUP_BY',''));" > mysql_setup_script.sql
              mysql --host=localhost --protocol=TCP --port=3306 --user=root --password='' --reconnect < mysql_setup_script.sql
            displayName: 'Configure mysql'

```

2023-04-26 13:46 UTC, anthonyburdi approved these changes
Approving pending tests pass (see suggested change).

2023-04-26 19:35 UTC, donaldheppner approved these changes

2023-04-26 22:46 UTC, merged