[FEATURE] DataProfilerColumnDomainBuilder
great-expectations/great_expectations pull request #7770
Opened 2023-04-28 19:56 UTC by alexjeilert

Changes proposed in this pull request:

- Updated `DataProfilerColumnDomainBuilder` class to remove profile_path instance variable.
- Updated `DataProfilerColumnDomainBuilder`'s `_get_domains()` function to take in profile_path, metric, and metric_values as a part of variables
- Updated DataProfilerTableColumnList to filter columns from the profile object by checking if the `metric` of the column is in `metric_values`
- Updated `test_data_profiler_column_domain_builder` and `test_data_profiler_structured_data_assistant` to match updated `DataProfilerColumnDomainBuilder` functionality

- [x] My code follows the Great Expectations [style guide](https://docs.greatexpectations.io/docs/contributing/style_guides/code_style)
- [x] I have performed a [self-review](https://docs.greatexpectations.io/docs/contributing/contributing_checklist) of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have added [unit tests](https://docs.greatexpectations.io/docs/contributing/contributing_test#writing-unit-and-integration-tests) where applicable and made sure that new and existing tests are passing.

2023-05-04 00:09 UTC, alexsherstinsky commented on contrib/capitalone_dataprofiler_expectations/capitalone_dataprofiler_expectations/metrics/data_profiler_metrics/data_profiler_table_column_list.py
> +        profile_report_filtered_column_names: list = []
@alexjeilert If we are filtering in this different way, then do we still need the use of GX metrics for this purpose (the `get_dbms_compatible_column_names()`) call?  Also, the filtering code can be shortened using a list comprehension.  Thank you.

2023-05-04 00:11 UTC, alexsherstinsky commented on contrib/capitalone_dataprofiler_expectations/capitalone_dataprofiler_expectations/rule_based_profiler/domain_builder/data_profiler_column_domain_builder.py
> -            parameter_reference=self.profile_path,
@alexjeilert Sounds like you are always going to use the `variables` key `profile_path`, so I can see how your simplification makes sense.  Thanks.

2023-05-04 00:13 UTC, alexsherstinsky commented on contrib/capitalone_dataprofiler_expectations/capitalone_dataprofiler_expectations/rule_based_profiler/domain_builder/data_profiler_column_domain_builder.py
> +        metric_values: str = get_parameter_value_and_validate_return_type(
@alexjeilert The name `metric_values` is not ideal here; I believe these are the parameters of the metric you are going to use, so I would suggest a more fitting name (whereas "metric value" usually refers to the value of a metric that was computed -- this appears to be different).  Thank you.

2023-05-04 00:16 UTC, alexsherstinsky commented on contrib/capitalone_dataprofiler_expectations/capitalone_dataprofiler_expectations/tests/rule_based_profiler/data_assistant/test_data_profiler_structured_data_assistant.py
> +            "metric_values": ["int", "float"],
@alexjeilert Please see my note above about possibly changing the name `metric_values` to something more intuitive for this purpose.  Thank you.

2023-05-04 00:18 UTC, alexsherstinsky commented on contrib/capitalone_dataprofiler_expectations/capitalone_dataprofiler_expectations/tests/rule_based_profiler/domain_builder/test_data_profiler_column_domain_builder.py
> -    VARIABLES_KEY,
@alexjeilert Now with the simplification of the `DomainBuilder`, are any of these tests duplicates, which could be deleted?  Thanks.

2023-05-04 00:18 UTC, alexsherstinsky requested changes
Please see comments inline.  Thank you!

2023-05-18 13:30 UTC, micdavis commented
The issues regarding this PR have been addressed in #7920. Please close this PR as the changes are being addressed in the other PR.

2023-05-18 15:39 UTC, alexsherstinsky commented
Closing per request by @micdavis -- thank you.

2023-05-18 15:39 UTC, closed without merging