[DOCS] Add another small fix to doc
great-expectations/great_expectations pull request #7960
Opened 2023-05-22 21:03 UTC by HaebichanGX

- [ ] Description of PR changes above includes a link to [an existing GitHub issue](https://github.com/great-expectations/great_expectations/issues)
- [ ] PR title is prefixed with one of: [BUGFIX], [FEATURE], [DOCS], [MAINTENANCE], [CONTRIB]
- [ ] Code is linted

    ```
    black .

    ruff . --fix
    ```
- [ ] Appropriate tests and docs have been updated

For more details, see our [Contribution Checklist](https://docs.greatexpectations.io/docs/contributing/contributing_checklist), [Coding style guide](https://docs.greatexpectations.io/docs/contributing/style_guides/code_style), and [Documentation style guide](https://docs.greatexpectations.io/docs/contributing/style_guides/docs_style).

After you submit your PR, keep the page open and **monitor the statuses of the various checks made by our continuous integration process at the bottom of the page. Please fix any issues that come up** and [reach out on Slack](https://greatexpectations.io/slack) if you need help. Thanks for contributing!

2023-05-22 22:00 UTC, Shinnnyshinshin approved these changes
LGTM :)

2023-05-22 22:04 UTC, tjholsman requested changes
@HaebichanGX could you add the same edit to the title in [the sidebar](https://github.com/great-expectations/great_expectations/blob/develop/docs/docusaurus/sidebars.js) which also appears to be mispelled?

2023-05-22 22:33 UTC, HaebichanGX commented
Oh @tjholsman I left it on auto-merge so it got merged before checking. I'll look through the docs and gather all the minor issues I see overall and create another PR that addresses many of these small issues.

2023-05-23 11:19 UTC, kwcanuck commented
@HaebichanGX thanks for identifying and correcting the typos. I've been doing my best to locate and clean up these issues, but a fresh pair of eyes is helpful. I used your branch to address some additional typos this morning. In future, you can add me as a reviewer to docs PRs - Rachel might be unavailable, or too busy to review.

2023-05-23 12:41 UTC, Rachel-Reverie approved these changes
Approved so I'm not blocking.  I flagged a few things for readability -- but I think we might want to review those `*args` and `*kwargs` definitions.  I'm pretty sure that they are supposed to indicate positional and named parameters passed to the function provided with the `function` parameter, but it currently reads ambiguously: it could also mean positional and named parameters being passed to the function that they are part of the definition of, which seems... kinda redundant to state, and doesn't explain what their use is, if so.

2023-05-23 12:41 UTC, Rachel-Reverie commented on great_expectations/dataset/dataset.py
> +            **kwargs       : Keyword arguments to be passed the function
```suggestion
            *args          : Positional arguments to be passed to the function
            **kwargs       : Keyword arguments to be passed to the function
```

2023-05-23 12:41 UTC, Rachel-Reverie commented on great_expectations/validator/validator.py
> +            **kwargs       : Keyword arguments to be passed the function
```suggestion
            *args          : Positional arguments to be passed to the function
            **kwargs       : Keyword arguments to be passed to the function
```

2023-05-23 12:41 UTC, Rachel-Reverie commented on great_expectations/data_asset/data_asset.py
> +            **kwargs       : Keyword arguments to be passed the function
```suggestion
            *args          : Positional arguments to be passed to the function
            **kwargs       : Keyword arguments to be passed to the function
```

2023-05-23 12:41 UTC, Rachel-Reverie commented on great_expectations/dataset/dataset.py
> +            **kwargs       : Keyword arguments to be passed the function
```suggestion
            *args          : Positional arguments to be passed to the function
            **kwargs       : Keyword arguments to be passed to the function
```

2023-05-23 12:41 UTC, Rachel-Reverie commented on great_expectations/validation_operators/validation_operators.py
> +                "provide a link the validation result. Please move all notification actions after "
```suggestion
                "provide a link to the Validation Result. Please move all notification actions after "
```

2023-05-23 12:41 UTC, Rachel-Reverie commented on tests/test_fixtures/rule_based_profiler/example_notebooks/DataAssistants_Instantiation_And_Running.ipynb
> +    "* There are multiple `DataAssistants` centered around a theme (volume, nullity and so on), and this notebook walks you through an example `VolumeDataAssistant` to show the capabilities and poten
```suggestion
    "* There are multiple `DataAssistants` centered around a theme (volume, nullity, and so on), and this notebook walks you through an example `VolumeDataAssistant` to show the capabilities and potential of this new interface."
```

2023-05-23 12:44 UTC, Rachel-Reverie commented on docs/docusaurus/docs/guides/expectations/how_to_edit_an_existing_expectationsuite.md
> +title: How to Edit an Expectation Suite
```suggestion
title: How to edit an Expectation Suite 
```

2023-05-23 16:41 UTC, tjholsman approved these changes

2023-05-23 20:35 UTC, merged