[FEATURE] Support DataFrame Argument in AbstractDataContext.get_validator()
great-expectations/great_expectations pull request #8094
Opened 2023-06-10 01:35 UTC by alexsherstinsky

### Scope
This change supports `dataframe` argument in `AbstractDataContext.get_validator()`.  Together with passing `validator` (instead of `batch_request`) to `Checkpoint.run()`, this provides support for ephemeral data in `Validator` and `Checkpoint` usage scenarios.

### Remarks
* JIRA: DX-469/DX-553

- [ ] Description of PR changes above includes a link to [an existing GitHub issue](https://github.com/great-expectations/great_expectations/issues)
- [x] PR title is prefixed with one of: [BUGFIX], [FEATURE], [DOCS], [MAINTENANCE], [CONTRIB]
- [x] Code is linted

    ```
    black .

    ruff . --fix
    ```
- [x] Appropriate tests and docs have been updated

For more details, see our [Contribution Checklist](https://docs.greatexpectations.io/docs/contributing/contributing_checklist), [Coding style guide](https://docs.greatexpectations.io/docs/contributing/style_guides/code_style), and [Documentation style guide](https://docs.greatexpectations.io/docs/contributing/style_guides/docs_style).

After you submit your PR, keep the page open and **monitor the statuses of the various checks made by our continuous integration process at the bottom of the page. Please fix any issues that come up** and [reach out on Slack](https://greatexpectations.io/slack) if you need help. Thanks for contributing!

2023-06-11 18:55 UTC, NathanFarmer requested changes
We should not need to pass the dataframe to the validator.

2023-06-11 19:25 UTC, alexsherstinsky commented
> We should not need to pass the dataframe to the validator.

@NathanFarmer I agree -- please see Remark 1 above, where the `dataframe` would be passed as part of a "Runtime" `BatchRequest` (non-serializable Pandas and Spark extensions of the standard FDS `BatchRequest`).

What do you think about this approach?  Thanks.

2023-06-14 13:12 UTC, NathanFarmer requested changes
Somehow my previous review was dismissed.

2023-06-14 16:00 UTC, alexsherstinsky commented
Indeed @NathanFarmer is correct -- thanks, @NathanFarmer for emphasizing the clean approach.  Indeed, we can cleanly obtain (at least in GX OSS) the `BatchRequest` and run `get_validator()` in a way that the `DataFrame` remains on `DataFrameAsset` without problems. Hence, I am closing this pull request.

2023-06-14 16:00 UTC, closed without merging