[MAINTENANCE] `Table.head()` update for `sqlalchemy`, so entire table is not queried
great-expectations/great_expectations pull request #8234
Opened 2023-07-03 20:51 UTC by Shinnnyshinshin

- [ ] Description of PR changes above includes a link to [an existing GitHub issue](https://github.com/great-expectations/great_expectations/issues)
- [ ] PR title is prefixed with one of: [BUGFIX], [FEATURE], [DOCS], [MAINTENANCE], [CONTRIB]
- [ ] Code is linted - run `invoke lint` (uses `black` + `ruff`)
- [ ] Appropriate tests and docs have been updated

For more details, see our [Contribution Checklist](https://docs.greatexpectations.io/docs/contributing/contributing_checklist), [Coding style guide](https://docs.greatexpectations.io/docs/contributing/style_guides/code_style), and [Documentation style guide](https://docs.greatexpectations.io/docs/contributing/style_guides/docs_style).

After you submit your PR, keep the page open and **monitor the statuses of the various checks made by our continuous integration process at the bottom of the page. Please fix any issues that come up** and [reach out on Slack](https://greatexpectations.io/slack) if you need help. Thanks for contributing!

2023-07-21 03:29 UTC, Shinnnyshinshin commented on great_expectations/expectations/metrics/table_metrics/table_head.py
> +            return df
What was previously the `df = None` case handled by its own helper method.

2023-07-21 03:30 UTC, Shinnnyshinshin commented on great_expectations/expectations/metrics/table_metrics/table_head.py
> +    def _sqlalchemy_head_pandas_less_than14(
The code here is mostly the same, just moved to its own helper method

2023-07-21 03:36 UTC, Shinnnyshinshin commented on great_expectations/self_check/util.py
> -
`table_name` can now be over-written if needed

2023-07-21 23:55 UTC, Shinnnyshinshin commented on great_expectations/expectations/metrics/table_metrics/table_head.py
> +    def _sqlalchemy_head_pandas_less_than14(
I hope to retire this method if we bump our minimum pandas to greater than 1.4

2023-07-24 13:56 UTC, anthonyburdi requested changes
Nice work! Just a few items to address.

2023-07-24 13:56 UTC, anthonyburdi commented on great_expectations/expectations/metrics/table_metrics/table_head.py
> +            # limit doesn't compile properly for mssql
Interesting, so for later pandas versions the limit compiles properly. Good find!

2023-07-24 13:56 UTC, anthonyburdi commented on tests/expectations/metrics/table_metrics/test_table_head.py
> +def test_head_table_name_not_fetch_all_2_rows(sqlalchemy_test_engine):
Please add some decorators to these tests.

2023-07-24 13:56 UTC, anthonyburdi commented on tests/expectations/metrics/table_metrics/test_table_head.py
> +    table_name = None
Sorry if I'm missing this - how is table name used in this test?

2023-07-24 13:56 UTC, anthonyburdi commented on tests/expectations/metrics/table_metrics/test_table_head.py
> +def test_head_table_name_is_anonymous_not_fetch_all(sqlalchemy_test_engine):
Up to you, but most of these tests only change a parameter or two - could be a good candidate for a parametrized test. Param IDs can be used to describe what is being tested (e.g. in place of the test function name). There are a few examples in the codebase, e.g. `test_generate_table_name_with_expectation` or just search for the decorator `@pytest.mark.parametrize`

2023-07-25 17:50 UTC, Shinnnyshinshin commented on tests/expectations/metrics/table_metrics/test_table_head.py
> +def test_table_head_sqlite(
@anthonyburdi the tests have been parametrized :)

2023-07-25 20:34 UTC, anthonyburdi approved these changes
LGTM! Thanks for the synchronous review :)

2023-07-26 00:36 UTC, merged