[DOCS]
great-expectations/great_expectations pull request #8554
Opened 2023-08-15 13:24 UTC by kwcanuck

In [DOC-541](https://greatexpectations.atlassian.net/browse/DOC-541), @Rachel-Reverie requested the addition of a new topic that documents the process of identifying failed rows in Expectations. This PR adds the new topic.

## Definition of done
- [X] PR title is prefixed with one of: [BUGFIX], [FEATURE], [DOCS], [MAINTENANCE], [CONTRIB]
- [X] _Appropriate_ tests and docs have been updated

2023-08-15 13:34 UTC, ghost commented
<details open>
<summary><b>👇 <a href="https://app.codesee.io/r/reviews?pr=8554&src=https%3A%2F%2Fgithub.com%2Fgreat-expectations%2Fgreat_expectations">Click on the image</a> for a new way to code review</b>
</summary>

####

[![Review these changes using an interactive CodeSee Map](https://s3.us-east-2.amazonaws.com/maps.codesee.io/images/github/great-expectations/great_expectations/8554/dae4a246/6be3c9e8db06c02b6bdee43ca4a5a84b596e605b.svg)](https://app.codesee.io/r/reviews?pr=8554&src=https%3A%2F%2Fgithub.com%2Fgreat-expectations%2Fgreat_expectations)

#### Legend
<img src="https://app.codesee.io/Legend_v3.png" alt="CodeSee Map legend" width="220" height="156">
</details>

2023-08-25 19:18 UTC, austiezr requested changes
No problems with content -- we are missing example code for two tabs at the end, not certain how necessary it is to be explicit with all possible backends for output.

2023-08-25 19:18 UTC, austiezr commented on docs/docusaurus/docs/guides/expectations/advanced/identify_failed_rows_expectations.md
> +</TabItem>
These are missing example code.

2023-08-28 16:52 UTC, kwcanuck commented on docs/docusaurus/docs/guides/expectations/advanced/identify_failed_rows_expectations.md
> +The following is an example of the information returned after running the Checkpoint. For SQLAlchemy, the utput includes a query that can be used directly against the database backend.
```suggestion
The following is an example of the information returned after running the Checkpoint. For SQLAlchemy, the output includes a query that can be used directly against the database backend.
```

2023-08-30 18:49 UTC, Shinnnyshinshin commented on docs/docusaurus/docs/guides/expectations/advanced/identify_failed_rows_expectations.md
> +The failed rows are defined as values in the `unexpected_index_column_names` parameter.  In the following example, you are setting the parameter to `event_id` to return the `event_ids` of the rows th
Thank you for this @kwcanuck :) love it

2023-08-30 18:49 UTC, Shinnnyshinshin commented on docs/docusaurus/docs/guides/expectations/advanced/identify_failed_rows_expectations.md
> +After you run the Checkpoint, a dictionary for each failed row is returned. Each dictionary contains the row’s identifier and the failed value.
❤️

2023-08-30 18:50 UTC, Shinnnyshinshin approved these changes
LGTM pending the clarification of the "dropdown" term that you mentioned @kwcanuck

2023-08-30 19:32 UTC, kwcanuck commented
@Shinnnyshinshin thanks for the quick review and your infinite patience! The content is now ready for your final review and (hopefully) approval.

2023-08-30 19:52 UTC, Shinnnyshinshin commented on docs/docusaurus/docs/guides/expectations/advanced/identify_failed_rows_expectations.md
> +The following image shows the `unexpected_index_list` values are displayed as part of the validation output. Click **To retrieve all unexpected values** to view the SQL query that you can use to retr
Looks great :)

2023-08-30 20:49 UTC, austiezr approved these changes
LGTM!

2023-08-31 19:52 UTC, Rachel-Reverie approved these changes
LGTM

2023-08-31 20:40 UTC, merged