Set merge_queue in CI pipeline and turn off auto-update
great-expectations/great_expectations pull request #8730
Opened 2023-09-18 18:59 UTC by TrangPham

- [ ] Description of PR changes above includes a link to [an existing GitHub issue](https://github.com/great-expectations/great_expectations/issues)
- [ ] PR title is prefixed with one of: [BUGFIX], [FEATURE], [DOCS], [MAINTENANCE], [CONTRIB]
- [ ] Code is linted - run `invoke lint` (uses `black` + `ruff`)
- [ ] Appropriate tests and docs have been updated

For more information about contributing, see [Contribute](https://docs.greatexpectations.io/docs/contributing/contributing_checklist).

After you submit your PR, keep the page open and **monitor the statuses of the various checks made by our continuous integration process at the bottom of the page. Please fix any issues that come up** and [reach out on Slack](https://greatexpectations.io/slack) if you need help. Thanks for contributing!

2023-09-18 23:54 UTC, Kilo59 commented on .github/workflows/ci.yml
> +    needs:
Why are these lines changing? Can you install the pre-commit hooks as they will prevent whitespace changes from accidentally being committed

2023-09-19 00:09 UTC, Shinnnyshinshin commented on .github/workflows/ci.yml
> +  merge_group:
🚀

2023-09-20 15:27 UTC, Kilo59 requested changes
Other than the whitespace changes, this looks good!
Can't wait!

2023-09-22 20:01 UTC, Kilo59 approved these changes

2023-09-22 20:24 UTC, merged