[CONTRIB][FEATURE]-add-threshold-parameter
great-expectations/great_expectations pull request #8891
Opened 2023-10-30 05:55 UTC by tb102122

add optional paramter for threshold to avoid sensitive results.

2023-11-01 21:02 UTC, anthonyburdi requested changes
Thanks for this contribution @tb102122! Would you mind removing the print statements before we merge?

2023-11-01 21:02 UTC, anthonyburdi commented on contrib/experimental/great_expectations_experimental/expectations/expect_multicolumn_datetime_difference_in_months.py
> +
```suggestion
```

2023-11-01 21:02 UTC, anthonyburdi commented on contrib/experimental/great_expectations_experimental/expectations/expect_multicolumn_datetime_difference_in_months.py
> +            print(diff_months)
```suggestion
```

2023-11-01 21:06 UTC, tb102122 commented on contrib/experimental/great_expectations_experimental/expectations/expect_multicolumn_datetime_difference_in_months.py
> +
Done sorry missed that from my testing

2023-11-01 21:08 UTC, tb102122 reviewed
let me know if anything else is needed

2023-11-02 14:25 UTC, anthonyburdi approved these changes
Thank you for this contribution!

2023-11-02 14:57 UTC, merged