[FEATURE] Update SnowflakeDatasource connection details
great-expectations/great_expectations pull request #8922
Opened 2023-11-02 19:11 UTC by Kilo59

- [ ] Description of PR changes above includes a link to [an existing GitHub issue](https://github.com/great-expectations/great_expectations/issues)
- [ ] PR title is prefixed with one of: [BUGFIX], [FEATURE], [DOCS], [MAINTENANCE], [CONTRIB]
- [ ] Code is linted - run `invoke lint` (uses `black` + `ruff`)
- [ ] Appropriate tests and docs have been updated

For more information about contributing, see [Contribute](https://docs.greatexpectations.io/docs/contributing/contributing_checklist).

After you submit your PR, keep the page open and **monitor the statuses of the various checks made by our continuous integration process at the bottom of the page. Please fix any issues that come up** and [reach out on Slack](https://greatexpectations.io/slack) if you need help. Thanks for contributing!

2023-11-15 14:57 UTC, Kilo59 commented on great_expectations/datasource/fluent/snowflake_datasource.py
> +            print(schema)
TODO: `OneOf`

2023-11-15 19:07 UTC, elenajdanova approved these changes
lgtm

2023-11-16 14:17 UTC, NathanFarmer requested changes
Even with the stub file changes...how to does this preserve auto-complete with everything nested inside of `connection_string`?

2023-11-16 14:18 UTC, NathanFarmer approved these changes
Nevermind, I see it was already in the stub file.

2023-11-16 16:25 UTC, merged

2023-11-16 16:26 UTC, anthonyburdi commented
Force merged after all CI checks passed to enable releasing today.