Change default for create_temp_table to False
great-expectations/great_expectations pull request #9116
Opened 2023-12-16 00:19 UTC by roblim

- [ ] Description of PR changes above includes a link to [an existing GitHub issue](https://github.com/great-expectations/great_expectations/issues)
- [ ] PR title is prefixed with one of: [BUGFIX], [FEATURE], [DOCS], [MAINTENANCE], [CONTRIB]
- [ ] Code is linted - run `invoke lint` (uses `black` + `ruff`)
- [ ] Appropriate tests and docs have been updated

For more information about contributing, see [Contribute](https://docs.greatexpectations.io/docs/contributing/contributing_checklist).

After you submit your PR, keep the page open and **monitor the statuses of the various checks made by our continuous integration process at the bottom of the page. Please fix any issues that come up** and [reach out on Slack](https://greatexpectations.io/slack) if you need help. Thanks for contributing!

2023-12-16 00:38 UTC, billdirks reviewed
Thanks for doing this! I have a few comments:

1. It looks like some tests are failing. Likely these depended on the old default value.
2. Have you manually verified that this fixes the observed issue? If you expect you will need other PRs to fix this issue, we can delay this check until later but we should manually verify the fix before releasing.
3. I'm not sure if the `_SQLAsset.get_batch_list_from_batch_request` is actually using this `create_temp_table` when it is populating `batch_spec_kwargs`. We should investigate though that can happen in a separate PR.
4. We should get this into `develop`. If we want to release in a `0.18.x` build, after we are happy with the fix we will need to make another PR into that branch.

2023-12-16 02:02 UTC, roblim commented
> Thanks for doing this! I have a few comments:
> 
> 1. It looks like some tests are failing. Likely these depended on the old default value.
> 2. Have you manually verified that this fixes the observed issue? If you expect you will need other PRs to fix this issue, we can delay this check until later but we should manually verify the fix before releasing.
> 3. I'm not sure if the `_SQLAsset.get_batch_list_from_batch_request` is actually using this `create_temp_table` when it is populating `batch_spec_kwargs`. We should investigate though that can happen in a separate PR.
> 4. We should get this into `develop`. If we want to release in a `0.18.x` build, after we are happy with the fix we will need to make another PR into that branch.

1. Took longer than expected, but fixed all the tests and everything is passing now.
2. Yep - confirmed that changes fix observed issue.
3. Was also able to confirm that it appears `_SQLAsset.get_batch_list_from_batch_request` is actually using this `create_temp_table`. Already had this call in notebook I've been using to test and that call only takes a few seconds now instead of 20 minutes.
4. Def want to release in a `0.18.x` build. Can discuss on our Monday call.

Thanks!

2023-12-16 14:22 UTC, NathanFarmer approved these changes

2023-12-16 20:11 UTC, billdirks approved these changes
Thanks for following up on all my questions!

2023-12-18 14:01 UTC, Kilo59 approved these changes

2023-12-18 14:28 UTC, Kilo59 commented on great_expectations/execution_engine/sqlalchemy_execution_engine.py
> +        create_temp_table: bool = False,
This shouldn't matter or need to change.
I'll look into this.

Probably also related to these issues
 1. https://github.com/great-expectations/great_expectations/issues/8147
 2. https://github.com/great-expectations/great_expectations/issues/8618
 3. https://github.com/great-expectations/great_expectations/issues/8325

2023-12-18 14:52 UTC, Kilo59 commented on great_expectations/execution_engine/sqlalchemy_execution_engine.py
> +        create_temp_table: bool = False,
That seems to be the issue.
We should revert this change once this merges 👇 
- https://github.com/great-expectations/great_expectations/pull/9118

2023-12-18 14:55 UTC, Kilo59 requested changes
I don't think we need to change anything about the execution engine itself.
This should obviate the need for changes there.
- https://github.com/great-expectations/great_expectations/pull/9118

2023-12-18 18:59 UTC, Kilo59 approved these changes

2023-12-18 19:21 UTC, merged