[FEATURE] Update pandas datasource to return a Batch instead of a Validator.
great-expectations/great_expectations pull request #9129
Opened 2023-12-19 00:04 UTC by billdirks

- [ ] Description of PR changes above includes a link to [an existing GitHub issue](https://github.com/great-expectations/great_expectations/issues)
- [ ] PR title is prefixed with one of: [BUGFIX], [FEATURE], [DOCS], [MAINTENANCE], [CONTRIB]
- [ ] Code is linted - run `invoke lint` (uses `black` + `ruff`)
- [ ] Appropriate tests and docs have been updated

For more information about contributing, see [Contribute](https://docs.greatexpectations.io/docs/contributing/contributing_checklist).

After you submit your PR, keep the page open and **monitor the statuses of the various checks made by our continuous integration process at the bottom of the page. Please fix any issues that come up** and [reach out on Slack](https://greatexpectations.io/slack) if you need help. Thanks for contributing!

2023-12-19 00:04 UTC, billdirks commented on great_expectations/datasource/fluent/pandas_datasource.py
> +        # BDIRKS, should only grab the last one, maybe do something better than this implementation
Delete note to self

2023-12-19 21:14 UTC, billdirks commented on tests/checkpoint/test_checkpoint.py
> -@pytest.mark.filesystem
We want to stop passing a validator to a checkpoint so I'm removing this test.

2023-12-19 22:26 UTC, billdirks commented on tests/integration/docusaurus/tutorials/quickstart/quickstart.py
> +# TODO: update where these expectations are imported
I'm tracking removing these TODOs in https://greatexpectations.atlassian.net/browse/V1-111

2023-12-20 00:03 UTC, billdirks commented on great_expectations/datasource/fluent/pandas_datasource.py
> +    def _get_batch(
All the functional changes are in the file. The other changes are tests/docs/pyi related.

2023-12-22 01:04 UTC, joshua-stauffer commented on tests/datasource/fluent/test_pandas_datasource.py
>          # read_* returns a validator, but we just want to inspect the asset
```suggestion
        # read_* returns a batch, but we just want to inspect the asset
```

2023-12-22 01:05 UTC, joshua-stauffer commented on tests/datasource/fluent/test_pandas_datasource.py
>          # read_* returns a validator, but we just want to inspect the asset
probably don't need to retrieve the asset one line below this, could just use the asset returned by the batch

2023-12-22 01:10 UTC, joshua-stauffer commented on tests/datasource/fluent/test_viral_snippets.py
> +    # context.view_validation_result(checkpoint_result)
do you intend to leave these in the PR?

2023-12-22 01:14 UTC, joshua-stauffer requested changes
thanks @billdirks, in general looks good! left a couple small comments. I wasn't able to comment on it because its on unchanged lines, but the docstrings for all these pandas methods need to be updated.

2024-01-02 21:10 UTC, joshua-stauffer approved these changes
thanks for addressing comments!

2024-01-02 21:24 UTC, merged