[DOCS] Customization of search bar
great-expectations/great_expectations pull request #9243
Opened 2024-01-17 15:30 UTC by deborahniesz

# Description

Customization of  [docsearch algolia](https://docsearch.algolia.com/docs/what-is-docsearch/) component to match the new mockup.

## Previous version: 
![Screenshot from 2024-01-17 12-27-04](https://github.com/great-expectations/great_expectations/assets/38264052/1908ccfa-7f9f-4a33-83d3-2473566d10fe)

## New version:
![Screenshot from 2024-01-17 12-24-51](https://github.com/great-expectations/great_expectations/assets/38264052/72d0441c-01f5-4cd3-9a16-4f3bc2048c9b)

## On hover:
![Screenshot from 2024-01-17 12-25-58](https://github.com/great-expectations/great_expectations/assets/38264052/db99b516-1ead-43bd-91e0-e6de8096f311)

- [ ] Description of PR changes above includes a link to [an existing GitHub issue](https://github.com/great-expectations/great_expectations/issues)
- [ ] PR title is prefixed with one of: [BUGFIX], [FEATURE], [DOCS], [MAINTENANCE], [CONTRIB]
- [ ] Code is linted - run `invoke lint` (uses `black` + `ruff`)
- [ ] Appropriate tests and docs have been updated

For more information about contributing, see [Contribute](https://docs.greatexpectations.io/docs/contributing/contributing_checklist).

After you submit your PR, keep the page open and **monitor the statuses of the various checks made by our continuous integration process at the bottom of the page. Please fix any issues that come up** and [reach out on Slack](https://greatexpectations.io/slack) if you need help. Thanks for contributing!

2024-01-17 15:36 UTC, deborahniesz commented
@cla-bot check

2024-01-25 13:13 UTC, kwcanuck approved these changes

2024-01-31 19:43 UTC, josectobar requested changes
This looks great! Just left a few comments. thanks!

2024-01-31 19:43 UTC, josectobar commented on docs/docusaurus/src/components/NavbarItems/GithubNavbarItem/index.js
Why is the Github logo not including the release version like it does in the designs? 

<img width="144" alt="image" src="https://github.com/great-expectations/great_expectations/assets/21246524/c1846462-3daf-4e49-88bc-ec2d6d1600a8">

2024-01-31 19:43 UTC, josectobar commented on docs/docusaurus/src/components/NavbarItems/GithubNavbarItem/index.js
> +                    </div>
nit pick: We should use spans here instead.
```suggestion
                    <span>
                        <img src={starIcon} alt="Github Stargazers Count"/>
                        {starsCount}
                    </span>
```

2024-01-31 19:43 UTC, josectobar commented on docs/docusaurus/src/components/NavbarItems/GithubNavbarItem/index.js
> +                    </div>
```suggestion
                    <span>
                        <img src={forkIcon} alt="Github Forks Count"/>
                        {forksCount}
                    </span>
```

2024-01-31 19:43 UTC, josectobar commented on docs/docusaurus/src/components/NavbarItems/GithubNavbarItem/index.js
> +    let forkIcon = useBaseUrl(`img/code-branch.svg`);
We should avoid using `let` if we're not re-assigning the variable.
```suggestion
    const githubMarkImg = useBaseUrl(`img/github-mark.svg`);
    const githubLogoImg = useBaseUrl(`img/github.svg`);
    const starIcon = useBaseUrl(`img/star.svg`);
    const forkIcon = useBaseUrl(`img/code-branch.svg`);
```

2024-01-31 19:43 UTC, josectobar commented on docs/docusaurus/src/components/NavbarItems/GithubNavbarItem/styles.module.css
> +    font-size: 0.75rem;
I think we should use a typography variable here.

2024-01-31 19:43 UTC, josectobar commented on docs/docusaurus/src/css/custom.scss
I'm not super familiar with Sass. is it possible that instead of putting all custom classes in this one single file, we add them into files and sub-folders?

e.g.:
```
└──custom/
    ├──githubBadge/
    │  └── github-badge.scss
    └──navbar/
       └── navbar.scss
```

2024-01-31 19:43 UTC, josectobar commented on docs/docusaurus/src/theme/NavbarItem/ComponentTypes.js
> +// See https://github.com/facebook/docusaurus/issues/7227.
👍🏽

2024-01-31 20:01 UTC, josectobar commented on docs/docusaurus/src/components/NavbarItems/GithubNavbarItem/index.js
Also, I'm not a fan of how the image flickers when you refresh the page or at first load. Maybe if we add a  min width to the container that shows the star/merge branch image and the count and we make the `showGithubBadgeInfo` true by default and only set it to false it if there's an error.

2024-01-31 23:08 UTC, JessSaavedra commented on docs/docusaurus/src/components/NavbarItems/GithubNavbarItem/index.js
We agreed to take that out during a meeting, as it was not such a relevant info and it's not something that's retrieved in the same endpoint that we're using now, so we had do two requests to github api instead of one. Also, if I recall correctly, the final amount of releases was not something that was already calculated in the API but we had to do some extra processing, maybe @deborahniesz can elaborate on the details

2024-02-01 14:44 UTC, deborahniesz commented on docs/docusaurus/src/components/NavbarItems/GithubNavbarItem/index.js
Yes, there is this workaround to avoid having to request all branches or tags since there was no endpoint that returned the total amount, but it seemed to be a waste to request all branches only to count the elements. So the solution was to request them all but with 1 element per page, so the endopoint only returns one element but the header of the response tells you how many pages there are in total, which would be the total amount of elements since you are requesting one per page
`function getElementCountFromGithubAPI(element) {

    fetch(`https://api.github.com/repos/great-expectations/great_expectations/${element}?per_page=1`)
        .then(response => {
            const headers = response.headers;
            const paginationLinks = headers.get('Link');
            return paginationLinks.split('per_page=1&page=')[2].split('>')[0] // get total pages
        })
}`
Still, since it was decided to only show stars and forks, this code was deprecated

2024-02-01 17:34 UTC, deborahniesz commented on docs/docusaurus/src/css/custom.scss
Yes you are right! 
I would leave the github badge css inside the github-badge component folder but the css for the searchbar I moved it from the generic custom.scss to its own file!

2024-02-01 18:16 UTC, SuperYeehee reviewed
Having some thoughts around the Hover effect on the Search. I think its a bit inconsistent with how our other 'Icon only' buttons are styled. Looking at the Feedback section, styling is a bit different. Will review the Button styling with Becca.  
Overall work looks great! Thank you!

2024-02-01 18:59 UTC, josectobar commented on docs/docusaurus/src/components/NavbarItems/GithubNavbarItem/index.js
Can we add a test for the logic on this component?

2024-02-08 01:46 UTC, josectobar approved these changes
👍🏽

2024-02-08 01:48 UTC, josectobar commented
I approved this but there's a step failing in CI was it doing this before?

2024-02-08 03:43 UTC, JessSaavedra commented
> I approved this but there's a step failing in CI was it doing this before?

I think it's because it was outdated related to develop, I updated the branch and now is passing!

2024-02-08 17:20 UTC, merged