[DOCS] Updating Tabs' Styles
great-expectations/great_expectations pull request #9287
Opened 2024-01-25 21:09 UTC by deborahniesz

# Description

Updated Tab styles to match mockup. Added a separated stylesheet to organize all tab changes (current styles and new ones).

The new styles are

 - Gray underline in Tabs group
 - Top borders are now rounded in the underline of a selected Tab .

[Jira Ticket](https://greatexpectations.atlassian.net/jira/software/c/projects/DSB/boards/79?issueParent=26175&selectedIssue=DSB-664)

- [ ] Description of PR changes above includes a link to [an existing GitHub issue](https://github.com/great-expectations/great_expectations/issues)
- [ ] PR title is prefixed with one of: [BUGFIX], [FEATURE], [DOCS], [MAINTENANCE], [CONTRIB]
- [ ] Code is linted - run `invoke lint` (uses `black` + `ruff`)
- [ ] Appropriate tests and docs have been updated

For more information about contributing, see [Contribute](https://docs.greatexpectations.io/docs/contributing/contributing_checklist).

After you submit your PR, keep the page open and **monitor the statuses of the various checks made by our continuous integration process at the bottom of the page. Please fix any issues that come up** and [reach out on Slack](https://greatexpectations.io/slack) if you need help. Thanks for contributing!

2024-01-26 18:19 UTC, kwcanuck approved these changes
I'm not a fan of the grey horizontal bar that displays when a tab isn't selected. I think this adds visual clutter and makes pages harder to scan quickly. I'll defer to the majority decision and the design experts. 

![image](https://github.com/great-expectations/great_expectations/assets/104205257/487465aa-a846-471d-9b1d-97659ff0e87c)

2024-02-01 00:07 UTC, josectobar commented on docs/docusaurus/src/css/tabs.scss
> +  margin-top: 0 !important;
Do we still need this?

2024-02-01 00:17 UTC, josectobar requested changes
Left a small question.

2024-02-01 00:17 UTC, josectobar commented on docs/docusaurus/src/css/tabs.scss
> +}
Same with this one, I noticed you moved these two but I can't tell where they're being applied

2024-02-02 13:44 UTC, josectobar approved these changes
Looks great!

2024-02-05 16:31 UTC, merged