[DOCS] Add resources dropdown to navbar
great-expectations/great_expectations pull request #9349
Opened 2024-02-01 09:17 UTC by JessSaavedra

# Description
- Adds resources dropdown to navbar
- Unifies help files from GX Cloud and GX Core into `how to get support`file

- [ ] Description of PR changes above includes a link to [an existing GitHub issue](https://github.com/great-expectations/great_expectations/issues)
- [ ] PR title is prefixed with one of: [BUGFIX], [FEATURE], [DOCS], [MAINTENANCE], [CONTRIB]
- [ ] Code is linted - run `invoke lint` (uses `black` + `ruff`)
- [ ] Appropriate tests and docs have been updated

For more information about contributing, see [Contribute](https://docs.greatexpectations.io/docs/contributing/contributing_checklist).

After you submit your PR, keep the page open and **monitor the statuses of the various checks made by our continuous integration process at the bottom of the page. Please fix any issues that come up** and [reach out on Slack](https://greatexpectations.io/slack) if you need help. Thanks for contributing!

2024-02-01 09:30 UTC, JessSaavedra commented on docs/docusaurus/docs/how_to_get_support.md
> +title: How to get support
This file will contain the unified info for support that will result of this documentation JIRA ticket: https://greatexpectations.atlassian.net/browse/DOC-649

I leave it here as a placeholder, but if by the time this PR is reviewed we don't have it yet, I can just hide the link in the navbar and add it later!

2024-02-05 22:53 UTC, JessSaavedra commented on docs/docusaurus/docs/how_to_get_support.md
> +title: How to get support
File is already merged so I'm deleting this one and redirecting to the existing one!

2024-02-06 01:01 UTC, josectobar requested changes
Looks great, just left a small comment for @kwcanuck to respond.

2024-02-06 01:01 UTC, josectobar commented on docs/docusaurus/docusaurus.config.js
> +              label: 'Expectations Gallery',
@kwcanuck, are we doing title case for headers?

2024-02-06 01:01 UTC, josectobar commented on docs/docusaurus/src/css/navbar.scss
> +    padding: 0.5em var(--ifm-navbar-padding-hoChan rizontal);
typo?
```suggestion
    padding: 0.5em var(--ifm-navbar-padding-horizontal);
```

2024-02-06 01:31 UTC, JessSaavedra commented on docs/docusaurus/src/css/navbar.scss
> +    padding: 0.5em var(--ifm-navbar-padding-hoChan rizontal);
oops, totally a typo :scream: good catch, fixed!

2024-02-07 16:45 UTC, kwcanuck commented on docs/docusaurus/docusaurus.config.js
> +              label: 'Expectations Gallery',
@josectobar, we use sentence case for topic and section headings.

2024-02-07 19:28 UTC, josectobar commented on docs/docusaurus/docusaurus.config.js
> +              label: 'Expectations Gallery',
Lets make these labels sentence 
```suggestion
              label: 'Expectations gallery',
```

2024-02-07 19:28 UTC, josectobar commented on docs/docusaurus/docusaurus.config.js
> +              label: 'Integration Support Policy',
```suggestion
              label: 'Integration support policy',
```

2024-02-07 19:30 UTC, josectobar approved these changes
I left a few small casing changes but will approve so you can merge this once they've been addressed.

2024-02-07 20:22 UTC, SuperYeehee approved these changes

2024-02-08 18:33 UTC, merged