[DOCS] Update alerts
great-expectations/great_expectations pull request #9407
Opened 2024-02-08 04:00 UTC by JessSaavedra

# Description
- Update styles from alerts
- Update styles from navigation buttons

# Screenshots
![Captura desde 2024-02-08 00-52-13](https://github.com/great-expectations/great_expectations/assets/7197057/f4b686f0-40cc-448c-b567-b6f4c1e912c0)
![Captura desde 2024-02-08 00-58-36](https://github.com/great-expectations/great_expectations/assets/7197057/45a0fea5-6ecc-461a-9eaf-59e7891c93e1)

- [ ] Description of PR changes above includes a link to [an existing GitHub issue](https://github.com/great-expectations/great_expectations/issues)
- [ ] PR title is prefixed with one of: [BUGFIX], [FEATURE], [DOCS], [MAINTENANCE], [CONTRIB]
- [ ] Code is linted - run `invoke lint` (uses `black` + `ruff`)
- [ ] Appropriate tests and docs have been updated

For more information about contributing, see [Contribute](https://docs.greatexpectations.io/docs/contributing/contributing_checklist).

After you submit your PR, keep the page open and **monitor the statuses of the various checks made by our continuous integration process at the bottom of the page. Please fix any issues that come up** and [reach out on Slack](https://greatexpectations.io/slack) if you need help. Thanks for contributing!

2024-02-11 23:34 UTC, SuperYeehee approved these changes

2024-02-12 15:48 UTC, SuperYeehee approved these changes

2024-02-14 19:42 UTC, josectobar requested changes
These alerts are looking great. I'm just leaving a few small suggestions. Thanks!

2024-02-14 19:42 UTC, josectobar commented on docs/docusaurus/src/theme/Admonition/Types.js
> +        </div>
I think we can replace the container with a `section` tag instead.
```suggestion
        <section>
            <h3>{props.title}</h3>
            <div>{props.children}</div>
        </section>
```

2024-02-14 19:42 UTC, josectobar commented on docs/docusaurus/src/theme/Admonition/index.js
> +  );
Can we use a switch instead? I think it'll be more appropriate considering the different cases.

```js
switch(type) {

case "cta":
 return  <Admonition {...props} icon={<CtaIcon/>} />;
....
....
etc
```

2024-02-14 23:28 UTC, josectobar approved these changes
Thank you for making these changes!

2024-02-15 17:02 UTC, merged