[DOCS] Was This Helpful section
great-expectations/great_expectations pull request #9426
Opened 2024-02-09 20:10 UTC by deborahniesz

- [ ] Description of PR changes above includes a link to [an existing GitHub issue](https://github.com/great-expectations/great_expectations/issues)
- [ ] PR title is prefixed with one of: [BUGFIX], [FEATURE], [DOCS], [MAINTENANCE], [CONTRIB]
- [ ] Code is linted - run `invoke lint` (uses `black` + `ruff`)
- [ ] Appropriate tests and docs have been updated

For more information about contributing, see [Contribute](https://docs.greatexpectations.io/docs/contributing/contributing_checklist).

After you submit your PR, keep the page open and **monitor the statuses of the various checks made by our continuous integration process at the bottom of the page. Please fix any issues that come up** and [reach out on Slack](https://greatexpectations.io/slack) if you need help. Thanks for contributing!

2024-02-10 00:01 UTC, josectobar commented on docs/docusaurus/src/components/WasThisHelpful/index.js
> +    </>
Can we add semantic tags here? ```suggestion
    return <div className={styles.feedbackCard}>
            <div className={styles.feedbackCardTitle}>
                <h3>Was this helpful?</h3>
            </div>
            <div className={styles.feedbackCardBody}>
                <img src={thumbsUpImg} className={styles.feedbackIcon}
                     alt="Thumbs up icon" onClick={handleThumbsUp}/>
                <img src={thumbsDownImg} className={styles.feedbackIcon}
                     alt="Thumbs down icon" onClick={handleThumbsDown}/>
            </div>
        </div>
```

2024-02-10 00:22 UTC, josectobar requested changes
This looks great, I think we still want to consider a couple of things we discussed today before merging this PR. Changing the thumbs up or down with something else, showing a different state after they click and adding this posthog key env variable during the CI job. I can add the key to the Github secrets. cc @joshzzheng

2024-02-10 00:22 UTC, josectobar commented on docs/docusaurus/src/components/WasThisHelpful/index.js
> +            </div>
We should be able to apply styling into the h3 directly. 
```suggestion
                <h3>Was this helpful?</h3>
```

2024-02-14 17:24 UTC, josectobar commented on docs/docusaurus/docusaurus.config.js
> +        apiKey: process.env.POSTHOG_API_KEY,
Can we leave a comment here that the prod key is stored in Netlify?

2024-02-21 19:52 UTC, josectobar reviewed
set env variable in run step

2024-02-21 19:52 UTC, josectobar reviewed
add env var step in run build

2024-02-21 23:07 UTC, josectobar commented on docs/docusaurus/.env.example
> +POSTHOG_API_KEY=
I don't think we need this anymore. can you instead add the instructions in the README that we should include the POSTHOG_API_KEY from our PostHog dev env in the run script? 

e.g. To test the `PostHog-Docusaurus` plugin, simply include the env var when running docusaurus locally: `start": "POSTHOG_API_KEY=BLABLABLA docusaurus start"`

2024-02-21 23:08 UTC, josectobar commented on docs/docusaurus/src/components/WasThisHelpful/index.js
> +                    <button className={feedbackSent ? styles.inactiveFeedbackButton : styles.feedbackButton} onClick={() => handleFeedbackReaction('test_docs.thumbs_up')}>Yes</button>
This should change to `yes` or `no` ```suggestion
                    <button className={feedbackSent ? styles.inactiveFeedbackButton : styles.feedbackButton} onClick={() => handleFeedbackReaction('test_docs.yes')}>Yes</button>
```

2024-02-21 23:09 UTC, josectobar commented on docs/docusaurus/src/components/WasThisHelpful/index.js
> +                    <button className={feedbackSent ? styles.inactiveFeedbackButton : styles.feedbackButton} onClick={() => handleFeedbackReaction('test_docs.thumbs_down')}>No</button>
```suggestion
                    <button className={feedbackSent ? styles.inactiveFeedbackButton : styles.feedbackButton} onClick={() => handleFeedbackReaction('test_docs.no')}>No</button>
```

2024-02-21 23:10 UTC, josectobar commented on docs/docusaurus/static/img/thumbs_down_icon.svg
We should remove this since it no longer applies

2024-02-21 23:10 UTC, josectobar commented on docs/docusaurus/static/img/thumbs_up_icon.svg
same here, lets remove this please

2024-02-21 23:50 UTC, josectobar commented
I haven't seen the latest designs but the padding feels a little weird. @SuperYeehee 
<img width="585" alt="image" src="https://github.com/great-expectations/great_expectations/assets/21246524/3e66ff42-e3d6-4136-afc9-46f0cafc785a">

2024-02-21 23:55 UTC, SuperYeehee commented
> I haven't seen the latest designs but the padding feels a little weird. @SuperYeehee <img alt="image" width="585" src="https://private-user-images.githubusercontent.com/21246524/306807812-3e66ff42-e3d6-4136-afc9-46f0cafc785a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg1NTk4MDUsIm5iZiI6MTcwODU1OTUwNSwicGF0aCI6Ii8yMTI0NjUyNC8zMDY4MDc4MTItM2U2NmZmNDItZTNkNi00MTM2LWFmYzktNDZmMGNhZmM3ODVhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjIxVDIzNTE0NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTM5YTEyMGJlOGIyZTFkZDNiYjIxMWU0NjAyODk1OGIzZjc5MzFmZTA3NmY1NzViNzY0YzEyNDU2YWFiMzM2ZjAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.4Slca7MYqV19Mp9ruMuPpeJdZJ0ToO0TKEjKAek5kRs">

Yes this is the latest design, I don't feel strongly on the padding since that component is centered within the page. I feel that if the padding was lower it would feel like our card designs for overview pages.

2024-02-22 01:07 UTC, josectobar commented
@deborahniesz, there are a few minor changes we should adjust but it's close to done.

2024-02-22 18:55 UTC, josectobar requested changes
Seems like I meant to submit these other comments but never did :D

2024-02-22 18:55 UTC, josectobar commented on docs/docusaurus/src/components/WasThisHelpful/index.js
> +            <hr className={styles.feedbackDivider}></hr>
```suggestion
            <hr className={styles.feedbackDivider}/>
```

2024-02-22 18:55 UTC, josectobar commented on docs/docusaurus/src/components/WasThisHelpful/index.js
> +                <div className={styles.feedbackCardActions}>
```suggestion
                <section className={styles.feedbackCardActions}>
```

2024-02-22 18:55 UTC, josectobar commented on docs/docusaurus/src/components/WasThisHelpful/index.js
> +            </div>
```suggestion
            </section>
```

2024-02-23 17:47 UTC, josectobar approved these changes
👍🏽

2024-02-23 18:11 UTC, merged