[FEATURE] `Checkpoint.save()`
great-expectations/great_expectations pull request #9676
Opened 2024-03-28 17:12 UTC by cdkini

- [ ] Description of PR changes above includes a link to [an existing GitHub issue](https://github.com/great-expectations/great_expectations/issues)
- [ ] PR title is prefixed with one of: [BUGFIX], [FEATURE], [DOCS], [MAINTENANCE], [CONTRIB]
- [ ] Code is linted - run `invoke lint` (uses `ruff format` + `ruff check`)
- [ ] Appropriate tests and docs have been updated

For more information about contributing, see [Contribute](https://docs.greatexpectations.io/docs/contributing/contributing_checklist).

After you submit your PR, keep the page open and **monitor the statuses of the various checks made by our continuous integration process at the bottom of the page. Please fix any issues that come up** and [reach out on Slack](https://greatexpectations.io/slack) if you need help. Thanks for contributing!

2024-03-28 19:31 UTC, joshua-stauffer commented on great_expectations/checkpoint/v1_checkpoint.py
> +            raise ValueError(f"Could not find existing Checkpoint '{self.name}' to update") from e
I think this error is too specific - for instance, if the cloud handler returns a 400 due to a field of an unexpected type.

2024-03-28 19:31 UTC, joshua-stauffer commented on great_expectations/core/factory/checkpoint_factory.py
> -    def __init__(self, store: CheckpointStore, context: AbstractDataContext):
🥳

2024-03-28 19:34 UTC, joshua-stauffer requested changes
left one comment around error handling

2024-03-28 19:44 UTC, cdkini commented on great_expectations/checkpoint/v1_checkpoint.py
> +            raise ValueError(f"Could not find existing Checkpoint '{self.name}' to update") from e
Hmm what error do we want to catch then? The other domain objects don't do error handling here but I don't want to raise a store backend error to the user (feels like that is more internal?)

2024-04-01 16:52 UTC, joshua-stauffer commented on great_expectations/data_context/store/checkpoint_store.py
> +            raise ValueError(f"Could not find existing Checkpoint '{name}' to update") from e
isn't this the same issue as before? There are other valid errors -- such as validation --  Cloud backend can throw, so this error message is too specific.

2024-04-01 16:53 UTC, joshua-stauffer requested changes
blocking because i believe error handling is still misleading

2024-04-01 17:11 UTC, joshua-stauffer approved these changes
thanks for addressing changes!

2024-04-01 18:35 UTC, merged